<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PatientWithName</name>
   <tag></tag>
   <elementGuidId>3622dfa6-5134-4efc-8c0b-df224a00958a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[starts-with(@id,'patient-name')][contains(@class,'PatientNameList')][normalize-space(text())='${fullName}']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[starts-with(@id,'patient-name')][contains(@class,'PatientNameList')][normalize-space(text())='${fullName}'][count(. | //*[@ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame']) = count(//*[@ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[starts-with(@id,'patient-name')][contains(@class,'PatientNameList')][normalize-space(text())='${fullName}']</value>
      <webElementGuid>2521e1fd-1606-4ca5-88e4-862a7e305f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>edf44f61-ec55-4443-a502-49dc7beaa149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[starts-with(@id,'patient-name')][contains(@class,'PatientNameList')][normalize-space(text())='${fullName}']</value>
      <webElementGuid>e80dc833-f287-4b8d-9436-6b57eec2b8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[starts-with(@id,'patient-name')][contains(@class,'PatientNameList')][normalize-space(text())='${fullName}']</value>
      <webElementGuid>59a959d2-fc83-4566-bade-c7090a2f5b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
