<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_blue_mic-status</name>
   <tag></tag>
   <elementGuidId>ecf80d55-6ffa-41a1-bd7a-ee3fd92b8bfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='items-center px-1 cursor-pointer border-b border-plum-600 bg-[#d6d6d4]']//*[@src = '/Blue-Mike.svg'][count(. | //*[@ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame']) = count(//*[@ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame'])]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='items-center px-1 cursor-pointer border-b border-plum-600 bg-[#d6d6d4]']//*[@src = '/Blue-Mike.svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aefe0546-faea-42f9-a1e0-2c62ee4040bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Blue-Mike.svg</value>
      <webElementGuid>234dbdfe-b140-47fa-ad4e-6e6ad0b3a30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>mic-status</value>
      <webElementGuid>95f8a7f2-74a4-4691-a6d1-e1c1de7aa114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4</value>
      <webElementGuid>9a425d11-8f2f-43d4-9c44-a39ab67da1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>2fa5144e-498b-4d10-8c8f-9c0db3452fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-64aec782ae1b26222fe63216778fef94</value>
      <webElementGuid>913e969a-1179-4e85-9cbb-7a923cc3731b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='items-center px-1 cursor-pointer border-b border-plum-600 bg-[#d6d6d4]']//*[@src = '/Blue-Mike.svg']</value>
      <webElementGuid>4238a2de-ab0b-4626-93ed-7ccc7507b3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>100dd536-107a-4cd0-accb-f7d1c0389025</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@class='items-center px-1 cursor-pointer border-b border-plum-600 bg-[#d6d6d4]']//*[@src = '/Blue-Mike.svg']</value>
      <webElementGuid>35b111bb-38c4-4154-b7b7-c21388f5c416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
