<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_grey_mic-status</name>
   <tag></tag>
   <elementGuidId>8a5db2b6-f633-4ec4-a968-f79e9e39349a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='items-center px-1 cursor-pointer border-b border-plum-600 bg-[#d6d6d4]']//*[@src = '/Grey-Mike.svg'][count(. | //*[@ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame']) = count(//*[@ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame'])]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='items-center px-1 cursor-pointer border-b border-plum-600 bg-[#d6d6d4]']//*[@src = '/Grey-Mike.svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>132ec0fb-0542-4d94-8b05-76d66e4a4589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Grey-Mike.svg</value>
      <webElementGuid>17ad6d3f-4bf1-4e24-bb45-638ea311cfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>mic-status</value>
      <webElementGuid>4dda83d1-3392-4ec7-aa33-7a7b19f78af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4</value>
      <webElementGuid>bd5754d7-e0d9-4671-b780-3208e1c53e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>1fdecb58-71b7-46e6-a3b1-1b0749f930b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-64aec782ae1b26222fe63216778fef94</value>
      <webElementGuid>98d9ebc7-aa1a-49e0-af9f-7070657ab8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='items-center px-1 cursor-pointer border-b border-plum-600 bg-[#d6d6d4]']//*[@src = '/Grey-Mike.svg']</value>
      <webElementGuid>4e9c1f0c-bc4b-4f0a-b341-d1d5b9153b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>8e0841a1-258a-4691-80fd-b12967086e7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@class='items-center px-1 cursor-pointer border-b border-plum-600 bg-[#d6d6d4]']//*[@src = '/Grey-Mike.svg']</value>
      <webElementGuid>c171c312-9da5-4307-aa9a-ddc7869287c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
