<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_calendar</name>
   <tag></tag>
   <elementGuidId>af19286b-ad8c-4195-946b-de101267ca73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[alt=&quot;calendar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@alt = 'calendar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;calendar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5d9aaa77-e5d7-45d9-a275-e9f0df1859a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/calender.svg</value>
      <webElementGuid>a5bdc64a-1695-4172-a272-9c8ca59e5b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>calendar</value>
      <webElementGuid>dd0899d3-bb83-40f9-8c10-d1dd0c581751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4</value>
      <webElementGuid>d20f868e-7422-494b-9e76-c9e687ecb664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-09f5700a47e1d40cc95a649f50944c1b</value>
      <webElementGuid>9adc01ea-3839-456d-801b-9818d1bd3277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@alt = 'calendar']</value>
      <webElementGuid>b438fd01-ca8e-45c9-93ae-0563d57c99e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>e92b2ec2-630a-4175-9060-d0414b00b901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@alt = 'calendar']</value>
      <webElementGuid>7ca14f0d-ba3a-407a-8ed5-b710237d8a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/calender.svg' and @alt = 'calendar']</value>
      <webElementGuid>0b595feb-100c-46a6-b67d-dbb976ada2cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
