<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PatientId</name>
   <tag></tag>
   <elementGuidId>a2f7c376-b39b-40b8-b7b3-adab0a9c2c1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='PatientHeaderSubSectionDiv']//span[contains(text(),'Patient ID')]/following-sibling::span/input)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#imgFindPatient</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Find Patient &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5475ea11-9dbc-4d81-8c41-ecb16c72c2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f5db78b5-279c-4631-83d4-d48475e046e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon search-icon</value>
      <webElementGuid>e0bd26e0-aa0a-45e3-96e0-cfecd5b25fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleFindPatient(this);</value>
      <webElementGuid>44c41ac7-949d-414c-9eea-52510da3586a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgFindPatient</value>
      <webElementGuid>fa101274-9d0e-4c9d-a3f6-eb8fe5e147ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Find Patient</value>
      <webElementGuid>afa80e86-9026-403a-9ad2-f4b7f1e37921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find Patient  </value>
      <webElementGuid>222a853b-3365-4685-a0c7-8b614e11cf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top_menu_container&quot;)/ul[@class=&quot;app-bar-menu place-right&quot;]/li[1]/a[@id=&quot;imgFindPatient&quot;]</value>
      <webElementGuid>f55d2cbf-b0e9-4312-b28d-f62e49964463</webElementGuid>
   </webElementProperties>
</WebElementEntity>
