<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnDataTransferEncBill</name>
   <tag></tag>
   <elementGuidId>d8f65088-0011-4e7f-b510-c2ae54c1b13e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDataTransferEncBill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btnDataTransferEncBill']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;TRANSFER&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02a482cd-b503-4f84-91db-9c30be0841db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea4e3ae6-b568-48ee-bc73-88c5b04a266f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button mini-button primary marT10 </value>
      <webElementGuid>3580a209-10b8-4d42-8453-86c7a0a9fb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TRANSFER</value>
      <webElementGuid>fd0c8ed5-5289-4ffd-8a2a-144313f9282b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDataTransferEncBill</value>
      <webElementGuid>7a6426dc-7c2f-4492-a51b-3cdd9d88e340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dataTransferFromEnc_FinalProcedureToSuperBill(this);</value>
      <webElementGuid>2089da41-ed4a-4f7a-9653-bb9e317c802c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f73afe4df7fc3cfd3d26c19ac6d09a3e</value>
      <webElementGuid>13b96ba3-0e67-4a47-a4dc-c8b4814b9d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btnDataTransferEncBill']</value>
      <webElementGuid>653d232c-6f36-420b-8f19-6d305f2fc43f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btnDataTransferEncBill']</value>
      <webElementGuid>153cef0c-1fc4-482a-ae66-f7156bd7d6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnDataTransferEncBill']</value>
      <webElementGuid>a057fb04-3961-42fa-bb58-6b2566d88aee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
