<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnDataTransferedEncBill</name>
   <tag></tag>
   <elementGuidId>d8f65088-0011-4e7f-b510-c2ae54c1b13e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='btnDataTransferEncBill' and @aria-invalid=&quot;false&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='btnDataTransferEncBill' and @aria-invalid=&quot;false&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a87ae6fd-0fcd-4322-9c75-480cfc0a2cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>753f063c-cdac-454a-9ee9-51ba91adeae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button mini-button primary marT10 </value>
      <webElementGuid>af979a38-0f63-4cb7-abf2-090bab84e0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TRANSFER</value>
      <webElementGuid>9f3266ae-f3cf-4a5f-81d7-51ce4e3501c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDataTransferEncBill</value>
      <webElementGuid>9da6fe5e-03dd-4206-a4aa-0b2794bdf951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dataTransferFromEnc_FinalProcedureToSuperBill(this);</value>
      <webElementGuid>e5932413-a7d4-4963-aa10-3c22761dfe7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f73afe4df7fc3cfd3d26c19ac6d09a3e</value>
      <webElementGuid>e0175ecc-410b-429b-b529-73b700493341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='btnDataTransferEncBill' and @aria-invalid=&quot;false&quot;]</value>
      <webElementGuid>c38090ee-990c-4a45-8268-556a10827189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id='btnDataTransferEncBill' and @aria-invalid=&quot;false&quot;]</value>
      <webElementGuid>d27e57d0-8390-40e9-bb63-07a59c598dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnDataTransferEncBill' and @aria-invalid=&quot;false&quot;]</value>
      <webElementGuid>f6939ce7-49d5-42ce-ac46-e98ebbc1b3ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
