<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toast_PatientEncounterSaved</name>
   <tag></tag>
   <elementGuidId>b476d469-6204-46a0-b872-80b1b39deb07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Patient encounter saved' or . = 'Patient encounter saved')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Patient encounter saved.' or . = 'Patient encounter saved.')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c86ef289-c489-452e-b755-0a9efe892b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jquery-notific8-message</value>
      <webElementGuid>36ee6d6b-4710-43fb-a1a7-01bf73416f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient encounter saved</value>
      <webElementGuid>7780b8c1-a19c-49c9-bc4a-5111adf70c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-38981c14e68cbc4c16bf9fa8bc135435</value>
      <webElementGuid>e21ba06d-2c88-46e0-9404-e5cc840c7a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[(text() = 'Patient encounter saved.' or . = 'Patient encounter saved.')]</value>
      <webElementGuid>0daa8a59-2a2c-48fb-8c38-d503e578c377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Patient encounter saved.' or . = 'Patient encounter saved.')]</value>
      <webElementGuid>dd3114b0-05f7-4e60-8965-955154179afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Patient encounter saved.' or . = 'Patient encounter saved.')]</value>
      <webElementGuid>888c6506-e140-4ac8-88f5-43d5500869c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
