<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Additional_Notes_EyeDiseases</name>
   <tag></tag>
   <elementGuidId>8c2d9f88-5c36-4b78-a5ca-2b43856cd71f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@name, 'Eye_Diseases.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@name,'Eye_Diseases.ADDITIONAL_NOTES')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b8379f46-6258-46a4-a50f-6bf0f81f58e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ef4937b-2127-4077-9f5e-5b0890ed8325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dfe4b544-0481-4684-bb4c-2b019cfcfc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>436f5987-2fe2-461d-b088-e2ec2160e42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8000</value>
      <webElementGuid>f171be7b-2025-4d19-ae40-b08a174a4b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>cbe73ec8-29a6-4ba8-a270-4042ef0d8256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Eye_Diseases.ADDITIONAL_NOTES</value>
      <webElementGuid>d04da105-2d83-4043-83c9-1008dd6cc799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2850</value>
      <webElementGuid>5a8024e0-9656-4a19-86ef-99665470252e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_ctrldispname</name>
      <type>Main</type>
      <value>Additional Notes</value>
      <webElementGuid>674f9df3-1f86-4d78-8787-7762874802b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>535f9a47-500e-47a0-9ddf-8ca9f9881870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>2058</value>
      <webElementGuid>247cdd41-aeb1-4d29-9457-381ccc54279d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>51c9636d-1e18-430a-9060-6f13c5423ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eyetype</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>6748267d-5727-42c0-9c79-97020b02a69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>9bc8d188-5c21-46c0-80ed-40b87d9222ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>4116</value>
      <webElementGuid>f08309df-c371-4a1b-9136-0b8fd2e6cf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-watermark</name>
      <type>Main</type>
      <value>Additional Notes</value>
      <webElementGuid>718c3d5b-6721-476b-b1ab-68a6ccb09bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>b8b2b039-2db7-45e9-8733-f41af839db20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-includeinsummaryelm</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>21ab29a7-7902-4102-8bd6-b7d1904d8ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Additional Notes</value>
      <webElementGuid>5f3bfe68-45a6-4a12-85b5-e563e189fb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f8c57bd-e069-43eb-b547-52ee58f2dc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Eye_Diseases.ADDITIONAL_NOTES</value>
      <webElementGuid>c143f573-6ca2-471c-98d0-330bff0e4e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>ADDITIONAL_NOTES</value>
      <webElementGuid>aaadfbda-e34f-46d9-b054-a83d8000aa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Eye_Diseases</value>
      <webElementGuid>0a54bec4-e4a2-47bc-af63-cc704ec9edd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6389c2b2-b0c4-4ed9-bceb-51c80d2f1617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c876d6ece77e9bca957c2792972d1786</value>
      <webElementGuid>4260bc06-d146-4ddf-af26-d58695ecd96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@name,'Eye_Diseases.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      <webElementGuid>44f59bb0-9a76-4554-a61f-11b961d1a33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[contains(@name,'Eye_Diseases.ADDITIONAL_NOTES')]</value>
      <webElementGuid>f8f5238a-7e70-4970-b759-00fa6c91e910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[contains(@name,'Eye_Diseases.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      <webElementGuid>0a3944fa-c288-4947-8468-5086e222d4a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
