<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnOfficeApptRechedule</name>
   <tag></tag>
   <elementGuidId>6b78cc43-c1ec-4e4f-9a86-4f222d187e5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnOffice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnOfficeApptRechedule']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OFFICE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fd89b27-6303-4bcb-a7f3-91d658854979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96548bca-eb67-4955-85e2-4b667003abee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmbar-btn-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1c963bad-556e-43cb-8719-c32058b68960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OFFICE</value>
      <webElementGuid>1b1f4ce2-e6ab-413d-9ce5-b20a27a9d98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold font20 hide-confirmation ignore-action-toggle margin-right-10px margin-top-10px notifationButton</value>
      <webElementGuid>6a1b9449-79e0-4205-8d9d-a468482222ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>136f534c-460e-46d3-8200-de55ad03bad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnOffice</value>
      <webElementGuid>eb2eba11-abe2-4183-99bf-b7fb54bbe3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnOffice&quot;)</value>
      <webElementGuid>1ab777fb-c3cb-47a9-9946-858182c15d6e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
