<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PM_scheduler_commonControlsBlock_select_2</name>
   <tag></tag>
   <elementGuidId>ab4d94f9-59fb-4870-94dc-985f17906f6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scheduler_commonControlsBlock_selectionDiv_clone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>((//table[@id=&quot;scheduler_containerBlock_vertTable&quot;]//tr[td//span[@class=&quot;dxsc-TimeRulerItemText&quot;][text()='9']]//following-sibling::tr/td[span[@class=&quot;dxsc-TimeRulerItemText&quot;][text()='45']])[1]//following-sibling::td)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#scheduler_commonControlsBlock_selectionDiv_clone</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d209a62d-db47-49aa-84ae-a236b13f2fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scheduler_commonControlsBlock_selectionDiv_clone</value>
      <webElementGuid>58762223-a8f9-4a37-8b6d-0e708eec6ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxscSel</value>
      <webElementGuid>c84bc35f-54a4-4cf5-ac1e-ec2cbf9b6518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scheduler_commonControlsBlock_selectionDiv_clone&quot;)</value>
      <webElementGuid>ff570159-0927-45d3-9303-3ed61c6264da</webElementGuid>
   </webElementProperties>
</WebElementEntity>
