<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PM_scheduler_commonControlsBlock_select_1</name>
   <tag></tag>
   <elementGuidId>9729fc84-d994-483f-9e2b-9cfd3676b366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scheduler_commonControlsBlock_selectionDiv_clone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>((//table[@id=&quot;scheduler_containerBlock_vertTable&quot;]//tr[td//span[@class=&quot;dxsc-TimeRulerItemText&quot;][text()='8']]//following-sibling::tr/td[span[@class=&quot;dxsc-TimeRulerItemText&quot;][text()='45']])[1]//following-sibling::td)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#scheduler_commonControlsBlock_selectionDiv_clone</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>272e1d11-0578-4270-a7d6-61a9f4d2cf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scheduler_commonControlsBlock_selectionDiv_clone</value>
      <webElementGuid>4f053357-6ead-4322-8315-d942e178f673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxscSel</value>
      <webElementGuid>8e5cff7d-d6b0-4e62-aba0-8a7472a8ddd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scheduler_commonControlsBlock_selectionDiv_clone&quot;)</value>
      <webElementGuid>3fc179e9-6fb8-4950-bf0a-2d6f9b73865e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
