<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmation_btnOffice</name>
   <tag></tag>
   <elementGuidId>ab56e8ef-dbce-4922-b76a-88e79c20d532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnOffice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnOffice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OFFICE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd86ff5f-8c42-4076-90a8-03cf7cae0535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>579cca0f-4d00-479d-844f-201ca3ab8651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmbar-btn-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d6f00643-ec4b-4637-8e2f-3b42b0fea8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OFFICE</value>
      <webElementGuid>dec250db-22fd-4864-8edf-d7976409dcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold font20 hide-confirmation ignore-action-toggle margin-right-10px margin-top-10px notifationButton</value>
      <webElementGuid>c0a9a2d1-63d0-4eb8-9907-28454b041e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>86341a65-4959-4e3b-9c08-4812d8f400cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnOffice</value>
      <webElementGuid>5e0cc450-bae8-4c4b-b898-47c8dbd2ece9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnOffice&quot;)</value>
      <webElementGuid>dd55cf36-7a09-41cf-aa57-a2e25c2ca6f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnOffice']</value>
      <webElementGuid>99eaad8e-9fd0-4cf0-b02b-ee995a5f6241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newConfirmationBarWithCustomButton']/div/div/div/div/div[2]/div/div[2]/div/input[3]</value>
      <webElementGuid>30025859-eb60-497c-8eb0-2ec6d214184e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input[3]</value>
      <webElementGuid>baf1328e-dab7-4d44-831b-e746c8189d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnOffice']</value>
      <webElementGuid>bd93681d-9e26-45d9-b460-def5188d3aa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
