<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Reason_ReasonId</name>
   <tag></tag>
   <elementGuidId>ad9e7283-ff95-424f-a6b7-bcce550bd8f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReasonId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ReasonId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ReasonId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>df9db8ab-2bba-471e-833e-8614adce73c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select select-default</value>
      <webElementGuid>7a0f2e68-3314-4bbe-b9bf-d9ce4517cee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>Reason</value>
      <webElementGuid>c208ddf2-05d5-44ec-b00c-8b01333bf37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>APPOINTMENTDETAILS</value>
      <webElementGuid>63bcf7fe-f6f7-4538-913b-88b1e5cbe7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>928e11c7-1a68-4b2d-be85-2c16399b1c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36dd9d99-5370-453c-a1c6-024900469daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field ReasonId must be a number.</value>
      <webElementGuid>b0471698-9caf-4584-90b5-cfb2b1a190fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReasonId</value>
      <webElementGuid>1c7eb6e0-4428-42b0-881f-23a609837ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReasonId</value>
      <webElementGuid>d6a72b2b-57a2-4756-90b8-2380a8a7ca17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>RefreshDataOnScheduleReasonChange(this);autoSyncRecallByReasonId();</value>
      <webElementGuid>a6b2d567-3f65-4c9e-8404-4051d042ce9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adjustment : Glasses Adjustments/repairCL FIT : CL FITTINGConsult : ConsultExam : New PatientIOP CK : Glaucoma Pressure CheckLASIK : Lasik EvaluationMisc. : MiscellaneousOCT Scan : OCT ScanPRP/OD : PRP Laser ODRecheck : RecheckT Fundus Photo : Fundus PhotosVisual Field : Visual Field Test</value>
      <webElementGuid>777e4971-f1c3-440a-a202-96f0d73bd2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReasonId&quot;)</value>
      <webElementGuid>e65e8707-4568-48ea-ab5f-31d1499636f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ReasonId']</value>
      <webElementGuid>8c88f544-a83f-4671-92a0-3ec9fb5e94dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CreateAppt']/div/div[2]/div/div/div/div/div/div/div/div/div[2]/span/select</value>
      <webElementGuid>738e4033-a174-499e-bd81-985d8cb6b443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason'])[3]/following::select[1]</value>
      <webElementGuid>22e1dc97-3c84-4e40-b832-ff09eb6feb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::select[2]</value>
      <webElementGuid>615a89b8-ac0d-473a-8984-873e559785b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/preceding::select[1]</value>
      <webElementGuid>5ed6ee8f-11a0-48c4-960b-c2e237a549ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Appt Reviewed &amp; Approved'])[1]/preceding::select[2]</value>
      <webElementGuid>5e3e1b85-7298-4c04-8d53-ccf165c47d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/span/select</value>
      <webElementGuid>254e0134-4cad-4b21-a540-f9e11d7f4a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ReasonId' and @name = 'ReasonId' and (text() = 'Adjustment : Glasses Adjustments/repairCL FIT : CL FITTINGConsult : ConsultExam : New PatientIOP CK : Glaucoma Pressure CheckLASIK : Lasik EvaluationMisc. : MiscellaneousOCT Scan : OCT ScanPRP/OD : PRP Laser ODRecheck : RecheckT Fundus Photo : Fundus PhotosVisual Field : Visual Field Test' or . = 'Adjustment : Glasses Adjustments/repairCL FIT : CL FITTINGConsult : ConsultExam : New PatientIOP CK : Glaucoma Pressure CheckLASIK : Lasik EvaluationMisc. : MiscellaneousOCT Scan : OCT ScanPRP/OD : PRP Laser ODRecheck : RecheckT Fundus Photo : Fundus PhotosVisual Field : Visual Field Test')]</value>
      <webElementGuid>0c0a27a1-0f68-4eaa-ac12-c08510833915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
