<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delete_dx-vam</name>
   <tag></tag>
   <elementGuidId>fb12b1b6-3588-47d1-a35e-c6bcdf7a225d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Apply_CD > span.dx-vam</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Apply_CD']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=/^Save Appointment$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8c9aec0f-2f66-4714-aab0-9a14666a9ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-vam</value>
      <webElementGuid>9475fdef-f229-400b-aec8-1976a7b6b114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Appointment</value>
      <webElementGuid>e6c877d5-6cfd-4134-bac3-8d870f958d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Apply_CD&quot;)/span[@class=&quot;dx-vam&quot;]</value>
      <webElementGuid>b0491299-66e6-45c5-9ad4-34659df72650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Apply_CD']/span</value>
      <webElementGuid>bfbe5e47-9fd9-4357-b36a-b07facfdb918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::span[2]</value>
      <webElementGuid>8f1ba5a0-937e-47d6-9d4c-9b5977b63a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/following::span[2]</value>
      <webElementGuid>d825d186-c8ff-4ea1-9946-41cb911ee5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data available'])[1]/preceding::span[1]</value>
      <webElementGuid>d6119758-13b4-4a55-a635-de9d5747f68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[8]/preceding::span[2]</value>
      <webElementGuid>dddec3b0-9ca6-4f3b-b156-729cac6ef237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save Appointment']/parent::*</value>
      <webElementGuid>bcb45856-2dfa-4754-90fc-347ce6114b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/span</value>
      <webElementGuid>17f3549b-2378-4fe4-b326-95311a9b2cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save Appointment' or . = 'Save Appointment')]</value>
      <webElementGuid>319c9902-0ea0-4442-a930-488e7d47d4fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
