<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MOOD_AFFECT</name>
   <tag></tag>
   <elementGuidId>06c915ed-61a9-4d60-9172-6467d5603833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@name,'Mental_and_Functional_Status.MOOD_AFFECT')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'Mental_and_Functional_Status.MOOD_AFFECT')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@name,'Mental_and_Functional_Status.MOOD_AFFECT')]</value>
      <webElementGuid>22a7d345-8b52-440f-9270-237992b51598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[contains(@name,'Mental_and_Functional_Status.MOOD_AFFECT')]</value>
      <webElementGuid>1583d92f-5887-402e-a21c-c71afa3dd607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[contains(@name,'Mental_and_Functional_Status.MOOD_AFFECT')]</value>
      <webElementGuid>f7002a4c-ff14-4b1c-bcc5-6c36030e19f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
