<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChiefComplaint</name>
   <tag></tag>
   <elementGuidId>8d6c2aca-4364-4e74-82b6-99069a4af3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,'.note.Complaint')])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(1) > .justify-between.flex.items-center span.text-sm[contenteditable=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,'.note.Complaint')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Vision has been kind of slightly off for a while now.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a27898b-2c32-4d01-8c29-25d66613b57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-black</value>
      <webElementGuid>3e21e26c-bf75-4aa5-aaae-4224fbb9602e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1dc6a4d7-bad1-42a7-b685-1a4335d3f6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>Subjective[0].note.Complaint</value>
      <webElementGuid>a6187274-f801-4390-9e5a-e0e84282f305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d78abe65dcd700428b444e3bd58d2498</value>
      <webElementGuid>e06f91f1-591f-46dc-a600-e34bf92dd4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,'.note.Complaint')])[1]</value>
      <webElementGuid>1213e0c8-045e-455b-8b32-ecefc0d0ca69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,'.note.Complaint')])[1]</value>
      <webElementGuid>38241f3d-c789-4730-99b9-0d13dfe338f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
