<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HPI</name>
   <tag></tag>
   <elementGuidId>24dbaf93-f495-4c3b-bbda-e30ad8035871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[span[text()='HPI:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.History&quot;)])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(2) > .justify-between.flex.items-center span.text-sm[contenteditable=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[span[text()='HPI:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.History&quot;)])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Patient reports vision has been slightly off for a while, which she attributes t&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61786021-0313-4c8c-93e6-2cac4e356d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-black</value>
      <webElementGuid>654b281d-36df-441f-b2de-498b340a0406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64b3694c-1bc8-4d89-965f-dff420e876d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>Subjective[1].note.History</value>
      <webElementGuid>7eab8867-6146-457e-bffe-f9e7f8bbe03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9b818a6e64288051c0072884a1b7340c</value>
      <webElementGuid>eabeecba-b089-48d8-8b48-b78c4eb84e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[span[text()='HPI:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.History&quot;)])[1]</value>
      <webElementGuid>a5a8ec28-0303-4db8-afc2-3740f7f569e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//*[span[text()='HPI:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.History&quot;)])[1]</value>
      <webElementGuid>415ae693-9a5e-4c8e-8359-4b4361c9a6e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
