<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Microphone access blocked</name>
   <tag></tag>
   <elementGuidId>72fa5f33-c383-45b2-ba93-ea40a71dbd2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()[normalize-space() = &quot;Microphone access blocked. Enable permission in browser settings&quot;]]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[text()[normalize-space() = &quot;Microphone access blocked. Enable permission in browser settings&quot;]][count(. | //*[@ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame']) = count(//*[@ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62d06640-e1a8-4ff6-8e19-4e333000b1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>99d1f110-e815-411d-8281-a718738801e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ae7983d5-20e9-4ba5-aa36-a0e8b57e4aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-in</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a839231-2621-49a6-a4bd-ea1bc70c678e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast Toastify__toast-theme--colored Toastify__toast--error Toastify__toast--close-on-click</value>
      <webElementGuid>64376ab1-a719-45f5-8469-47c5f890d2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>0c427fc6-fb48-4794-887f-9f1ad121b68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Microphone access blocked. Enable permission in browser settings</value>
      <webElementGuid>02dd2f0f-a5f6-49df-b0c8-f6ea5400b816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d000f3a456ddefb21d0d1d8af1b5fa8b</value>
      <webElementGuid>e6c28ded-e9cf-459a-b3d4-a5f3ba944702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()[normalize-space() = &quot;Microphone access blocked. Enable permission in browser settings&quot;]]</value>
      <webElementGuid>c0a6d555-dd67-413b-b922-2908475e369f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>b74dc730-9f78-4bba-a8a7-9dc8464e10b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[text()[normalize-space() = &quot;Microphone access blocked. Enable permission in browser settings&quot;]]</value>
      <webElementGuid>af71bea4-7e39-4d01-8d9b-323080c742e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[text()[normalize-space() = &quot;Microphone access blocked. Enable permission in browser settings&quot;]]</value>
      <webElementGuid>0e0242e8-b32f-4589-88dd-53b0319c290c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
