<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iFrame</name>
   <tag></tag>
   <elementGuidId>8952770b-06cd-454e-ac01-9166e63e9264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='myIframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#myIframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#myIframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1142d828-bf00-4b5b-95ca-bedf5c9cf768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myIframe</value>
      <webElementGuid>4ca5119d-b8a6-45dc-8f8f-7bc91a4b2877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://reactscribeui.evaa.ai:443/E1/demoscribe278/SAuLpR/Home/Index2?UserName=PankajP&amp;FirstName=Pankaj&amp;LastName=Pathade&amp;Email=pankajp@first-insight.com&amp;token=02f1eac9c6d011f09c276045bd311b38&amp;userId=0&amp;GlobalUserId=B57D75C1-5E5C-4ED4-8C70-0BB5035C19EE&amp;Status=</value>
      <webElementGuid>d52a2566-4d9f-414d-abea-b61b0e3068af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>microphone</value>
      <webElementGuid>c15c76a7-8ec6-4ee0-96eb-80941fc79fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myIframe&quot;)</value>
      <webElementGuid>3564ca05-fb5f-421a-a66c-57b0a74c835b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='myIframe']</value>
      <webElementGuid>af01018f-0ac8-4020-952d-d81352f63873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframeContainer']/iframe</value>
      <webElementGuid>4af5af52-c9f5-4a76-9b20-bffde172e606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cb864f09-6319-4c04-8777-0fcf895d0e60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
