<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChiefComplaint</name>
   <tag></tag>
   <elementGuidId>68739e5e-df40-40fc-9800-0df3c9b4d1f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(1) > .justify-between.flex.items-center span.text-sm[contenteditable=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,'.note.Complaint')])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,'.note.Complaint')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Vision has been kind of slightly off for a while now.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>047d3015-b2da-4e49-b843-011c178bae6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-black</value>
      <webElementGuid>6506243f-2562-49ba-9e68-259138c64b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ec2389e-965f-4301-a937-fba5c5ed5885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>Subjective[0].note.Complaint</value>
      <webElementGuid>21880d83-c8b0-4b0b-9ba2-b0c673a4e646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d78abe65dcd700428b444e3bd58d2498</value>
      <webElementGuid>b6944e8b-63e1-47e3-a2e5-9484c5a8f520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,'.note.Complaint')])[1]</value>
      <webElementGuid>d842289d-4969-472e-b758-76de76f7b81f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,'.note.Complaint')])[1]</value>
      <webElementGuid>1e76172f-03f4-4490-b1f2-8d8579cbbc0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
