<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Medications</name>
   <tag></tag>
   <elementGuidId>7162063f-7de7-4262-8411-256bb15d8d6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd58a989-728c-405b-910f-42db87090ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brand Name: Pat a day</value>
      <webElementGuid>d4aaf3e5-cb21-411c-9c16-798902115d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d919c45cdb61e1dfdd5df8e916ac87bf</value>
      <webElementGuid>a10deb74-65f7-453a-a3cc-2c0de18b7ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      <webElementGuid>60d3f88e-11b8-4a27-aa11-bd4c4ef4bb25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      <webElementGuid>d65d53de-9c9e-4cda-b9cc-7a0cc40e0ef0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
