<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Recording stopped</name>
   <tag></tag>
   <elementGuidId>edf616d7-64a1-4cc8-bb26-c9a94aa0e3b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' Toastify__toast ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.Toastify__toast</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '1' and (text() = 'Recording stopped; segment will append after processing' or . = 'Recording stopped; segment will append after processing') and @ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Recording stopped; segment will append after processing&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22611239-2a11-4311-bdbc-40385e3a8b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>719d7869-c03f-4796-8424-2bddcea3d177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5513b2c7-990e-4f9d-9cc0-cd36affe766f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-in</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b185d7b0-91ec-4ce0-b5e4-3026c556693f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast Toastify__toast-theme--colored Toastify__toast--info Toastify__toast--close-on-click Toastify--animate Toastify__bounce-enter--top-right</value>
      <webElementGuid>dabea47c-5942-4cc9-b104-12b0c50db0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>826ba91b-a104-4633-b34a-ae9b82f42505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recording stopped; segment will append after processing</value>
      <webElementGuid>90420658-9af8-458b-ae79-6f3b4c18e168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d000f3a456ddefb21d0d1d8af1b5fa8b</value>
      <webElementGuid>2ad2f8d3-c614-4ccb-896d-ddd8116e31da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' Toastify__toast ')]</value>
      <webElementGuid>19be7bbb-b614-4e69-8c3a-ea564d508607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>b997bfbe-26b8-4145-b827-6014e0662630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' Toastify__toast ')]</value>
      <webElementGuid>58122521-7b1a-42f5-a833-7478af53490e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1' and (text() = 'Recording stopped; segment will append after processing' or . = 'Recording stopped; segment will append after processing')]</value>
      <webElementGuid>f11a0a20-336a-4017-8dac-0da895d5673b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
