<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aetna_underline</name>
   <tag></tag>
   <elementGuidId>6113a8e3-71ce-4ebc-a0b4-db73bef0239d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblPatientRecords']/tbody/tr[2]/td/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.fixedGridTR.even > td.align-center.truncateWord > span.data-hj-whitelist > a.underline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;165464&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e47cdaf9-4f14-4684-998c-62c356f060a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>165464</value>
      <webElementGuid>5228f1f8-0e2f-4099-b6c6-1a39cd2f8785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline</value>
      <webElementGuid>750c2b43-c698-4883-91e2-7c60f922b967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 165464</value>
      <webElementGuid>949a9358-6ee5-4320-af7e-28bf8023a809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblPatientRecords&quot;)/tbody[@class=&quot;fixedGridTbody&quot;]/tr[@class=&quot;fixedGridTR even&quot;]/td[@class=&quot;align-center truncateWord&quot;]/span[@class=&quot;data-hj-whitelist&quot;]/a[@class=&quot;underline&quot;]</value>
      <webElementGuid>e9897018-a17b-461e-856e-207fdbad58ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblPatientRecords']/tbody/tr[2]/td/span/a</value>
      <webElementGuid>85ccfb92-8621-447e-bbc4-440872614716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'165464')]</value>
      <webElementGuid>4bbcdbd9-6d2f-411d-b7f8-f1b3e7e739d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aetna'])[2]/following::a[1]</value>
      <webElementGuid>fbacece1-d3ab-4e0f-b628-4335e9662ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(121) 211-1212'])[1]/following::a[1]</value>
      <webElementGuid>c700f979-e576-42c7-9d65-dc71ab3412dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[2]/preceding::a[1]</value>
      <webElementGuid>beb44a51-7467-4641-a8b7-cd27c05e9778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rahul'])[1]/preceding::a[1]</value>
      <webElementGuid>e4c04efc-f22f-4c3b-9060-bc5cb3d9f6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='165464']/parent::*</value>
      <webElementGuid>741f7615-26c4-4125-ba77-30c4e3010890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/span/a</value>
      <webElementGuid>618cd57d-5ecf-4708-ba0f-89f132f34aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = '165464' and (text() = ' 165464' or . = ' 165464')]</value>
      <webElementGuid>64d38965-000d-4e03-a098-7912752bedf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
