<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Getting MaximEyes ready_mif-home font1_5ca900</name>
   <tag></tag>
   <elementGuidId>71ad93f4-2741-4015-bf7b-e127106c5cd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navItemHome']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mif-home.font19.head-icon-shadow.fg-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ec1996b-a8b9-438e-a436-38b9fa4fbee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mif-home font19 head-icon-shadow fg-white</value>
      <webElementGuid>cad8d03a-16ff-4100-ab1a-f6512ae35311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top_menu_container&quot;)/ul[@class=&quot;app-bar-menu&quot;]/li[2]/a[@id=&quot;navItemHome&quot;]/span[@class=&quot;mif-home font19 head-icon-shadow fg-white&quot;]</value>
      <webElementGuid>73c93da9-0486-4b78-820c-ab30505f94a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navItemHome']/span</value>
      <webElementGuid>cda6006d-3b37-40ac-8bf8-aebbe7c9cd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>ad9cc510-05d6-4fb0-a53f-91037019b7e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
