<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divCurrentEyeSymptoms</name>
   <tag></tag>
   <elementGuidId>4562770f-31c9-4daa-99f6-7106e6207a8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@data-elementname=&quot;Current_Eye_Symptoms&quot;])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@data-elementname=&quot;Current_Eye_Symptoms&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-elementname=&quot;Current_Eye_Symptoms&quot;])[1]</value>
      <webElementGuid>6fc33f13-2e56-42f0-8277-b62ce817d65a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@data-elementname=&quot;Current_Eye_Symptoms&quot;])[1]</value>
      <webElementGuid>a2e1ecfd-1d89-4501-bfdd-5b8c2475a00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//div[@data-elementname=&quot;Current_Eye_Symptoms&quot;])[1]</value>
      <webElementGuid>390f3263-d7bc-4cfb-b473-8bcf2fe8d9ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
