<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CurrentEyeSymptoms</name>
   <tag></tag>
   <elementGuidId>f10c4547-42f7-49ed-b7d3-eb26527512ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@name , 'Current_Eye_Symptoms.${inputId}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\34 115\.Current_Eye_Symptoms\.GLARE_NOTES&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and contains(@name, 'Current_Eye_Symptoms.${inputId}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;\34 115\.Current_Eye_Symptoms\.GLARE_NOTES&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5079b49e-46d0-4ed4-ae3d-956968a46a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e5f5d78-cc13-4139-84c3-12a97df3c8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c486f0b-fcc3-4821-b0e1-254e6540b7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8000</value>
      <webElementGuid>091eb74a-3e44-405b-95ae-3e932035096c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>341ab856-0a84-4c44-a259-a6433bb8967c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>07c1ef6c-e5d2-4f9c-ad5c-a85a0dc72510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>9130c6c4-0c4e-44c3-abd0-2a1cacfd77f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Current_Eye_Symptoms.${inputId}</value>
      <webElementGuid>ee36a5d6-bcb7-444d-9f8c-addf6b00fe79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2012</value>
      <webElementGuid>2b36aa0a-6aa2-4cde-817a-bf1556d3afc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f279ee83-ce87-4010-b216-bed2906645d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>1946</value>
      <webElementGuid>5b709a71-bc02-49b7-9cac-d9060ab9fe6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>29404e07-8b05-499c-a943-46be0b12bf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eyetype</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>b8113f63-dbb5-4da8-90d1-3a6009227a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>2138</value>
      <webElementGuid>9db595fa-ee6a-46bb-a988-1026e1febb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>4115</value>
      <webElementGuid>d9dd9af4-f1ee-42e7-ad7a-e682dfa3e3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-supportclearbtn</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>31daa98f-0cb8-493e-be5f-0211add34700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clearable</value>
      <webElementGuid>83d2e115-d8b6-4bb0-aaa2-a4b449f527ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1582fba9-90ea-4bf2-a992-05f843e6d83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Current_Eye_Symptoms.${inputId}</value>
      <webElementGuid>e6d909b4-3360-401e-9c71-a22d4ebfcac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>${inputId}</value>
      <webElementGuid>e1a555cc-a2a9-4f2f-b1a3-345e3fe56acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9f41eee-be20-4264-a5ea-86f7ab946a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c2915e1bb11d77ea177a7bf0e1147af5</value>
      <webElementGuid>9c56d3fe-849e-4e6d-ada0-2bee72fc5756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@name , 'Current_Eye_Symptoms.${inputId}')]</value>
      <webElementGuid>6fdaa974-74eb-46db-ac66-8a097ad0a9ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[contains(@name , 'Current_Eye_Symptoms.${inputId}')]</value>
      <webElementGuid>e179708d-2089-454c-bcdc-d58c4afcafad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and contains(@name , 'Current_Eye_Symptoms.${inputId}')]')]</value>
      <webElementGuid>a010fac5-b4b1-4909-9388-2934a96042da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
