<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Additional_Notes_CES</name>
   <tag></tag>
   <elementGuidId>61133d3c-5424-4ddf-a40d-07067f4e2772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@name, 'Current_Eye_Symptoms.NOTES') and @placeholder = 'Additional Notes']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@name , 'Current_Eye_Symptoms.NOTES')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>23c650a6-5158-414a-b61e-4bc9f70d2b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e44c616c-10cb-446b-9b4c-faf1ce7e06ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3fbaf8b-42af-405f-83b1-3e8be0daafa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>964ea8c1-e610-4cd2-91b9-507510d6abbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8000</value>
      <webElementGuid>8e1ea347-ba4b-4a00-afb4-360a8458ac16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>923871f8-d270-4015-8bde-41e9aff60668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Current_Eye_Symptoms.NOTES</value>
      <webElementGuid>f24ac9d0-a49d-48c8-bab9-cdf3276c76db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2065</value>
      <webElementGuid>63b0ef99-cda0-4b5b-b2cd-d7943d905828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_ctrldispname</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>39b379b8-0516-477b-a94e-811e7f6dd7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>10a025c8-b604-4d2c-9d5c-20bdbaf6e660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>1960</value>
      <webElementGuid>7014b1ee-d98e-408d-8795-b1705f2afccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>391f5a30-ace5-4f5e-b1b6-2d8832fa5eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eyetype</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>29f2e3ea-9899-41d7-81f5-4cea05fcf418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>2138</value>
      <webElementGuid>f77f92a7-2ec2-4d00-b284-e8934101fad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>4115</value>
      <webElementGuid>3bd1dfbd-962b-48e5-bc45-6e9fe0af6b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-watermark</name>
      <type>Main</type>
      <value>Additional Notes</value>
      <webElementGuid>640271fe-afc4-4216-80d4-15ce9789fdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>1fe7cbc1-e439-404a-8971-2a9123215463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-includeinsummaryelm</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>1208a160-901d-41c9-9e0f-71f347c15070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Additional Notes</value>
      <webElementGuid>4b4d5303-c3b0-4f61-852e-38fe7632c0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>65d20bde-3d8c-4685-a991-c1d0aa7c324d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Current_Eye_Symptoms.NOTES</value>
      <webElementGuid>5eb4362f-8bcf-402d-96ab-989e6eac2013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>NOTES</value>
      <webElementGuid>48ea5c5c-db6c-4e6b-8e05-12812788d089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Current_Eye_Symptoms</value>
      <webElementGuid>d121ac55-c586-4ba2-86df-9e64f43627b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>233d2559-95df-4981-8ad8-cd7db1e8ed7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-95e4ac3335235b84fdac5dbbf7a964b0</value>
      <webElementGuid>111daf9e-f075-4a85-8a68-8c87afad5061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@name , 'Current_Eye_Symptoms.NOTES') and @placeholder = 'Additional Notes']</value>
      <webElementGuid>f255774f-25a1-47f1-9723-b9ccd8955815</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[contains(@name , 'Current_Eye_Symptoms.NOTES')]</value>
      <webElementGuid>a713ec44-6b11-4c1d-a073-fede2ace5c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[contains(@name , 'Current_Eye_Symptoms.NOTES') and @placeholder = 'Additional Notes']</value>
      <webElementGuid>0edc7e17-882c-4497-993c-232dc380e941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
