<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div Plans</name>
   <tag></tag>
   <elementGuidId>ecf54f9e-1473-4c41-9d28-d5652092784f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#encounterPlansData</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'encounterPlansData']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#encounterPlansData</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf4363c3-7b48-48d4-95c5-700866dd6581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>encounterPlansData</value>
      <webElementGuid>7c4a6b6a-fd57-43ee-be4d-3084944eb62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>encounterPlansData</value>
      <webElementGuid>2650f43b-9349-4946-af46-adbde36d643f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2fef2311-990a-488f-8872-71de8ef28aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orignal-height</name>
      <type>Main</type>
      <value>109px</value>
      <webElementGuid>fa016db7-1727-4d25-896d-a3734793b15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5d96f77362db33ed5fd70f57b35524fb</value>
      <webElementGuid>93df8d82-38db-4b40-9597-669950e3d62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'encounterPlansData']</value>
      <webElementGuid>3d8f9cd7-18d1-49a6-8da3-e8e3c552d582</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'encounterPlansData']</value>
      <webElementGuid>df4ccf36-90ab-4dfc-abf2-78c486a8b211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'encounterPlansData']</value>
      <webElementGuid>53682dac-8a90-43df-8f15-8fad46ec44bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
