<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div Plans</name>
   <tag></tag>
   <elementGuidId>ecf54f9e-1473-4c41-9d28-d5652092784f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'encounterPlansData']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#encounterPlansData</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'encounterPlansData']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#encounterPlansData</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>da7cadb8-11cc-4a05-9663-58d7045ece2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>encounterPlansData</value>
      <webElementGuid>967503d4-567d-43a4-b87d-7bc9a94c2c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>encounterPlansData</value>
      <webElementGuid>11d96c83-d3c3-41a7-84c5-30a2058f893b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>86860aa7-7925-4f89-973b-b74db6650881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orignal-height</name>
      <type>Main</type>
      <value>109px</value>
      <webElementGuid>3a98f70a-6b03-4c6f-8de2-2242c315cb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5d96f77362db33ed5fd70f57b35524fb</value>
      <webElementGuid>427180d4-e4e2-4bcb-a5b6-4413b173e3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'encounterPlansData']</value>
      <webElementGuid>5be0ab45-90c4-4b35-9e7c-e226609f206c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'encounterPlansData']</value>
      <webElementGuid>0b6ef995-ec4d-4519-abb1-63929ff80c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'encounterPlansData']</value>
      <webElementGuid>a7a3b11a-6547-4d39-8c72-ccb39feb8394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
