<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea Assessments</name>
   <tag></tag>
   <elementGuidId>57415ad6-1f9b-4de5-8f53-9c80ab9a9843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@name , 'Final_Diagnoses.ASSESSMENT')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@name , 'Final_Diagnoses.ASSESSMENT')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f329c5c2-ee11-47ae-bd2b-b0aef39aa0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d7234d51-4e66-43f9-9862-0da8126624b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95492208-346c-40ff-aff1-8e7ee5fabaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>29253ad5-ab04-4f27-a6ae-7c7b13038696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b1f35e9b-4d01-4341-8df2-37f2b86c9367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>06fd8966-6488-4dcd-909f-f4086cd042a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>2234.Final_Diagnoses.ASSESSMENT</value>
      <webElementGuid>6b705f49-f24d-4e5e-8a2e-46e6ae5d354a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7011</value>
      <webElementGuid>a88729cc-cd60-4fb3-ab11-d885cc9d4e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_ctrldispname</name>
      <type>Main</type>
      <value>Assessment</value>
      <webElementGuid>0c464054-2f23-47c0-bc7c-f90ec5e58905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0e19aa16-d4a7-4d55-82dd-3f9524f10d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>1706</value>
      <webElementGuid>86c9d168-a159-490b-ae09-bc15c46fbe51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f476026-3691-46f9-aead-1312d122bc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eyetype</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>463a9d0c-e5cb-4ef7-96ae-31578d6f4cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>2121</value>
      <webElementGuid>c905b098-4b12-4fe8-891d-6469f6643fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>Patient's vision has been slightly off, potentially related to blood sugar levels.
Visual field testing showed a couple of missed spots, which were not considered significant.
Patient is currently using Pataday daily for allergies.,Patient's vision has been slightly off, potentially related to blood sugar levels.
Visual field testing showed a couple of missed spots, which were not considered significant.
Patient is currently using Pataday daily for allergies.</value>
      <webElementGuid>61ec1473-0008-49d6-bd11-abd5e83156d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-supportclearbtn</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>51b4bfd4-f206-4982-b7da-d1b9d0485a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>2234</value>
      <webElementGuid>c0dc1d73-a665-4a9c-b2f1-ba846c3e86f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>expandTextarea(this)</value>
      <webElementGuid>5a68c052-cdba-4031-983a-a6f202f7e466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>expandTextarea(this)</value>
      <webElementGuid>5f7f2baf-ff32-482f-bf42-9703b1579158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>restoreOriginalSize(this)</value>
      <webElementGuid>f6863b5b-7673-4c74-a03e-d0f6611540c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Patient's vision has been slightly off, potentially related to blood sugar levels.
Visual field testing showed a couple of missed spots, which were not considered significant.
Patient is currently using Pataday daily for allergies.;Patient's vision has been slightly off, potentially related to blood sugar levels.
Visual field testing showed a couple of missed spots, which were not considered significant.
Patient is currently using Pataday daily for allergies.</value>
      <webElementGuid>ca04d040-530f-43a3-9c06-d78ef5938dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2a11b0b5-a22c-4813-ac6b-ff1c89cdee29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Final_Diagnoses.ASSESSMENT</value>
      <webElementGuid>1f1ad835-8a8e-4e9b-adc2-871eed0c5a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>ASSESSMENT</value>
      <webElementGuid>5e1f757f-d4c7-46e9-8ed4-8fc5a1951af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Final_Diagnoses</value>
      <webElementGuid>0886d2a2-2c39-44f9-941d-038f97822182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>674c2f1c-e773-41b3-815b-10018633b073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0dd371eb9327cb66cc7bb761deb343fd</value>
      <webElementGuid>ee5b81a8-ab3c-40ab-be8a-40b921e01a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@name , 'Final_Diagnoses.ASSESSMENT')]</value>
      <webElementGuid>e49b4f34-a170-4110-9790-845719189556</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[contains(@name , 'Final_Diagnoses.ASSESSMENT')]</value>
      <webElementGuid>4a6e0623-74fd-41ea-8d54-54c17105aad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//*[contains(@name , 'Final_Diagnoses.ASSESSMENT')]</value>
      <webElementGuid>80c33263-f5da-41f5-8aae-df80af87e07f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
