<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea HPI Notes</name>
   <tag></tag>
   <elementGuidId>9e1484e9-f855-49fe-a0d0-26507fde8fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@name , 'Chief_Complaint.EXTENDED_HPI')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@name, 'Chief_Complaint.EXTENDED_HPI')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\34 089\.Chief_Complaint\.EXTENDED_HPI&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[name=&quot;\34 089\.Chief_Complaint\.EXTENDED_HPI&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c75b75a9-b7b6-4334-85c9-5aabdafe46b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9928664d-cec3-4345-a0c7-158606575935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>336f2ed3-8395-4691-b5b4-e5d5b4e3acd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>84a0fc9b-f752-472d-a567-66493080e654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2500</value>
      <webElementGuid>aa2b2edf-6835-462d-9d89-e1a13dc86869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>d6d2989e-586b-45f4-84de-fc3894680ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Chief_Complaint.EXTENDED_HPI</value>
      <webElementGuid>cbca2636-8c51-47c7-9857-3e2e65b67f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3013</value>
      <webElementGuid>e1fcfffc-07c1-4b1d-8a55-bd2461653f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_ctrldispname</name>
      <type>Main</type>
      <value>HPI Notes</value>
      <webElementGuid>90142c90-ff57-45d7-906d-490a71e5d15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>baafd2e6-c0be-4516-8a65-3f171cd35573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>104</value>
      <webElementGuid>00c64fef-dcb4-4dd2-a57b-2d7be7e4f373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>838088f4-650d-432c-93fd-6a7306e71376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eyetype</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>dd9c2dba-a035-4f63-be30-dd33fa6700a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>2116</value>
      <webElementGuid>e7ac7356-17c3-475a-86ed-069cf6b5e550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-includeinsummaryelm</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>99f6a56b-8ca2-4c4d-a327-11bdc1b852ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>4089</value>
      <webElementGuid>d0df1a64-1005-45cc-98a0-868ca2a0b193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>a63d6cc8-a786-4d84-b403-b4ff5fb5cf37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>expandTextarea(this)</value>
      <webElementGuid>1c997960-e168-4d96-8301-648a1a561080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>expandTextarea(this)</value>
      <webElementGuid>c4cbe03a-fc0d-4082-82d2-9c0b8887c162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>restoreOriginalSize(this)</value>
      <webElementGuid>61ae4d4b-a345-4b54-b7fa-db39362b1217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a05656d-bbe0-4776-9f68-efbd62763ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Chief_Complaint.EXTENDED_HPI</value>
      <webElementGuid>ed81cb9a-59f8-4c7d-93cf-c25d9ad4f499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>EXTENDED_HPI</value>
      <webElementGuid>7f1673d6-d845-4ca6-955d-ebcd67bab189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Chief_Complaint</value>
      <webElementGuid>86702d10-bce0-40cd-8735-816bc6ac1d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7e708726-155e-4ec1-bd5e-17b33a73f9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-00ed16800c15975358b99e071f03ed3e</value>
      <webElementGuid>438f65f8-9fa3-4264-abbf-607240c978b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '4089.Chief_Complaint.EXTENDED_HPI']</value>
      <webElementGuid>10dde5b1-08df-4b97-ab97-1548cfb38367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[contains(@name , 'Chief_Complaint.EXTENDED_HPI')]</value>
      <webElementGuid>464247e6-a98d-4aee-9eef-c5f774f597a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = '4089.Chief_Complaint.EXTENDED_HPI']</value>
      <webElementGuid>fda201dd-077b-44bb-8415-097cfd47a9d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
