<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea Patient Chief Complaint</name>
   <tag></tag>
   <elementGuidId>a759d386-4215-4105-94f2-a7191092e975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@name , 'Chief_Complaint.CHIEF_COMPLAINT')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\34 089\.Chief_Complaint\.CHIEF_COMPLAINT&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[name=&quot;\34 089\.Chief_Complaint\.CHIEF_COMPLAINT&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bb7885cc-1fe4-4c00-ace0-07fff9fee4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e257980e-64f2-4965-ba9a-570660e353df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6de8aefc-95a9-4ec5-b6dc-e568c94d21d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44d7596b-6169-4f08-888c-71e6b13ca6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2500</value>
      <webElementGuid>5c6ee4ab-2ea0-4366-97f0-434c5ac8511a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>3e23f4b4-69f7-4a54-ac23-4e2d3d4d00c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>4089.Chief_Complaint.CHIEF_COMPLAINT</value>
      <webElementGuid>0305924c-dcb5-4f21-ab4a-ec01a3a96dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3012</value>
      <webElementGuid>52b557f2-ba0f-41a7-958d-d912e00c75af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_ctrldispname</name>
      <type>Main</type>
      <value>Pt Complaint</value>
      <webElementGuid>c9b0bada-0c7c-4bc3-8f10-8d1c3c01359d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a66fdfb9-9074-4709-b878-db41682ed7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>103</value>
      <webElementGuid>221cf1e0-f969-43f5-bf6e-f7026ba261e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>02e8648d-b83d-432e-bfb6-12081367c9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eyetype</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>c49c7246-a1cb-4898-b0df-9c433ea364ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>2116</value>
      <webElementGuid>fcc9d0a8-96a3-4cfb-83b1-7ed46d62e09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-includeinsummaryelm</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>fad83923-76c2-441e-80ce-0a38c0fe0303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>4089</value>
      <webElementGuid>2ef2d95b-86f5-4f71-a589-702f357ba2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>0879a065-488d-499f-a2a6-790c2e0e5128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>expandTextarea(this)</value>
      <webElementGuid>2929fba6-270d-47c5-aa46-1b9fe3c5d8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>expandTextarea(this)</value>
      <webElementGuid>e8808829-0e74-4bae-bead-43ad0364ecf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>restoreOriginalSize(this)</value>
      <webElementGuid>b14714f6-ab5d-4986-bbc0-8188a9073b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>07b58333-be3b-483e-b102-f8292eeb6899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Chief_Complaint.CHIEF_COMPLAINT</value>
      <webElementGuid>d742fee1-320f-4609-be14-9ab29f0dca83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>CHIEF_COMPLAINT</value>
      <webElementGuid>68b91e8d-3a62-4846-9b6e-49ecb117ff1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Chief_Complaint</value>
      <webElementGuid>eb1141a5-e1cc-4f20-8f40-36075386544f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2b9034b6-129a-4377-88d8-9cf052b61371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7d9be0bb5faf73eba745d5c520bc2342</value>
      <webElementGuid>5f34315f-fc9a-42fa-9bfb-010c2f5d88a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '4089.Chief_Complaint.CHIEF_COMPLAINT']</value>
      <webElementGuid>4cf80879-e9fa-4128-96b1-a9ee80287a11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[contains(@name , 'Chief_Complaint.CHIEF_COMPLAINT')]</value>
      <webElementGuid>81aa0582-9eeb-4506-826c-e9299c342f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = '4089.Chief_Complaint.CHIEF_COMPLAINT']</value>
      <webElementGuid>1d8c6028-6e6b-4c07-8682-9180217e186c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
