<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Refractions</name>
   <tag></tag>
   <elementGuidId>0eb59b91-1745-4ad2-ae9e-e28b2c964deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[contains(@name,'Refractions.NOTES')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;3477.Refractions.NOTES&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[contains(@name,'Refractions.NOTES')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[name=&quot;\33 477\.Refractions\.NOTES&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8adf1f8c-eec8-4b11-82e8-9452c8cabd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3361e51d-a24c-4502-8ed1-bbe41defcbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5f9683b8-fc87-49b5-ae87-e5c8f2774171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>178a2722-80d8-445b-88d7-ac26a6b598a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>94449656-3817-4582-8042-c7675f2b1013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>25c7c3eb-1e41-419d-8711-9b34b4c6f2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Refractions.NOTES</value>
      <webElementGuid>59068440-8b84-49f1-b699-9cc7265c10a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6444</value>
      <webElementGuid>dd02995f-43d4-4738-9da4-b870192326b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_ctrldispname</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>f22c67db-9a82-48ad-9649-02d118979671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af3db3fc-927b-4f3d-bb16-0f05d64e3be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>1838</value>
      <webElementGuid>f79d18f9-089c-45d9-8441-b41207f78260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2d29b794-cbda-4dbc-9f4f-7e06d8017a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>7247</value>
      <webElementGuid>71a26b8c-d870-4ee1-b9e1-c585d1f4022d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-watermark</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>7a58d295-a342-460d-9cc0-148e5e32e0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>793cf56b-3c33-430c-bdbf-e0d4b6ec25b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>3477</value>
      <webElementGuid>a97c426f-dd83-4e9b-9da3-d346d93c3a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>80770fe9-bc9d-451c-b86f-75fd63b6fc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setUserInitials(this)</value>
      <webElementGuid>55e222f7-9112-4261-a5d3-985253b3518d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b89e07db-4ff3-4c01-bf04-bbfe8bcc9ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Refractions.refrectionPanel</value>
      <webElementGuid>4d71e934-ca9b-4d50-87a5-fa0bc74f7da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>NOTES</value>
      <webElementGuid>fa5e4543-7f04-4b6a-a383-0cf2fd88e222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Refractions</value>
      <webElementGuid>09d8d681-ae2f-49f2-bcbe-1b6ab8b664f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enctabcomplexontrol</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb0d8903-2d42-4891-bbc9-e853540146f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3dae90e3-e71d-4a46-8e9a-f83b6c2a2454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@name,'Refractions.NOTES')]</value>
      <webElementGuid>77155d2c-d9cd-45ee-8567-0146f4cb1154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[contains(@name,'Refractions.NOTES')]</value>
      <webElementGuid>1564358f-b8bf-4514-9788-5839c7c2d616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='encformbase18a1c12093']/div/div[5]/div/div/div[2]/textarea</value>
      <webElementGuid>1fe208f7-2155-474a-bcc0-818577d1f0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/textarea</value>
      <webElementGuid>3a27fb4f-6236-4897-8589-63d682eb9bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[contains(@name , 'Refractions.NOTES') and @placeholder = 'Notes']</value>
      <webElementGuid>a0021f22-e0b9-4aed-83b1-e2844ff62e29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
