<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChiefComplaint</name>
   <tag></tag>
   <elementGuidId>0e9e1e29-bde5-46a9-9097-3a1b680eb51f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.Complaint&quot;)])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.Complaint&quot;)])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(1) > .justify-between.flex.items-center span.text-sm[contenteditable=&quot;true&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Vision has been kind of slightly off for a while now.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f96ad63-e6d6-4c2a-9f13-99c2ffbda2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-black</value>
      <webElementGuid>099bee68-31da-4396-8196-dd46fbbf4925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41f3e50e-e05c-4ad9-b396-3cd726cdc0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>Subjective[0].note.Complaint</value>
      <webElementGuid>3862d499-98d9-4418-9464-b97a7fb40558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d78abe65dcd700428b444e3bd58d2498</value>
      <webElementGuid>2a883608-0f59-4145-8c5a-445f05d0d272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.Complaint&quot;)])[1]</value>
      <webElementGuid>c3ae5dbb-f19c-4315-82ca-c5f4a7aa350d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>27519367-0050-44d2-a559-db209a3da0f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//*[span[text()='ChiefComplaint:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.Complaint&quot;)])[1]</value>
      <webElementGuid>9e50b75d-107b-4663-a02e-2c49857cbc80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
