<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HPI</name>
   <tag></tag>
   <elementGuidId>425982c5-3d28-4e63-87f8-f7be0922febe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[span[text()='HPI:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.History&quot;)])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[span[text()='HPI:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.History&quot;)])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(2) > .justify-between.flex.items-center span.text-sm[contenteditable=&quot;true&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Patient reports vision has been slightly off for a while, which she attributes t&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5e6cbeae-4def-4594-accd-ec95e718c3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-black</value>
      <webElementGuid>4402bf6f-e499-40b0-9c30-b145dec318aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c5a4b85-2a1f-4433-b5c5-57698a064048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>Subjective[1].note.History</value>
      <webElementGuid>43f86a0b-6fd8-4e45-bb87-b39f7c2443ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9b818a6e64288051c0072884a1b7340c</value>
      <webElementGuid>638719ed-4023-43f8-b0c3-a8f37a3c17f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[span[text()='HPI:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.History&quot;)])[1]</value>
      <webElementGuid>d0147a8d-1c90-49cb-8067-fc348b06b4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>be6e4ced-03c2-4a40-ba35-478d4d770974</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//*[span[text()='HPI:']]/following-sibling::span/descendant-or-self::span[contains(@data-path,&quot;.note.History&quot;)])[1]</value>
      <webElementGuid>5a6479ec-7561-41f6-a940-4e214744b899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
