<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Medications</name>
   <tag></tag>
   <elementGuidId>f075fbda-7d38-4af8-b599-da1580516f37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b105e8fd-7844-4e62-acb8-503588d5bc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brand Name: Pat a day</value>
      <webElementGuid>1a7a8e0c-6fc2-4c59-8efc-3b51f7d1ec8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d919c45cdb61e1dfdd5df8e916ac87bf</value>
      <webElementGuid>77d58b45-a70e-4eff-915a-45ec432bccf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      <webElementGuid>bfcba9aa-f4d8-4359-b93f-25e8977c8f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>8a5ac017-bf05-46c7-9423-1dbaa2f960e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      <webElementGuid>5e9dfefb-b93f-456e-aaac-6f179b1f5e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
