<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EncounterId</name>
   <tag></tag>
   <elementGuidId>83768c49-d2a0-4802-827c-25a49f74e23f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EncounterTypeID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=&quot;ptExamno&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EncounterTypeID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>691bb87f-3752-4f90-8b5c-59522fe6aa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3fd57a0c-6f36-476c-9d4e-fdaa3173e425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field EncounterTypeID must be a number.</value>
      <webElementGuid>7d800ff4-6bc3-4060-a8ca-9099cadc3fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Encounter Type is required</value>
      <webElementGuid>84264c4c-ac20-47d5-ab2f-a6ab56ebd687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EncounterTypeID</value>
      <webElementGuid>9c15feaf-00a9-48fc-b570-9fc6f20988df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EncounterTypeID</value>
      <webElementGuid>b2f304dd-80ea-45a4-bff9-7f88ee7d9e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>encounterTypeChange(this)</value>
      <webElementGuid>8fbb17d6-4be3-4291-928b-66099a250a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annual Vision ExamAnnual Vision Exam - TrainingCL Follow UpGlasses CheckMedical ExamNew Patient Exam</value>
      <webElementGuid>7a804f94-fcc3-4bcb-8e50-84404fa57d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EncounterTypeID&quot;)</value>
      <webElementGuid>c4a6d360-294b-4219-97a7-9851f72fc2d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
