<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProviderId</name>
   <tag></tag>
   <elementGuidId>9c3fb0e0-7eb6-4e1c-83aa-16ba7d775567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[starts-with(@id,&quot;ProviderID_&quot;)])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EncounterTypeID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EncounterTypeID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bf80a689-8024-4506-827a-e1f7e1d938d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66b7e85b-a8f4-4258-bb5a-ca671e57e507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field EncounterTypeID must be a number.</value>
      <webElementGuid>a4342abe-5ed5-469b-9f64-43f426b00f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Encounter Type is required</value>
      <webElementGuid>56404bb3-c45a-4b4e-8630-d0e736dbe45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EncounterTypeID</value>
      <webElementGuid>0ab84c22-c50d-45d4-a252-84c42abf9d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EncounterTypeID</value>
      <webElementGuid>ab0966ec-4558-49fc-894a-b19c03d95f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>encounterTypeChange(this)</value>
      <webElementGuid>d867fe67-4ab5-4bf8-ae30-f66d60f9d3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annual Vision ExamAnnual Vision Exam - TrainingCL Follow UpGlasses CheckMedical ExamNew Patient Exam</value>
      <webElementGuid>9ad816fa-1d25-4325-929f-527823cff49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EncounterTypeID&quot;)</value>
      <webElementGuid>cac96d39-6e6c-47f3-b753-c9bda558b68d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
