<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CLEAR</name>
   <tag></tag>
   <elementGuidId>494af5ca-588f-4514-b4de-ddcdf14d6aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@onclick = 'clearSearch()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[onclick=&quot;clearSearch\(\)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;CLEAR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32de4aef-db6f-4f59-bf7a-aa904bfa419a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button mini-button gray marR5</value>
      <webElementGuid>2ccfa768-d0e5-494e-9987-d5a3856f4c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clearSearch()</value>
      <webElementGuid>ac0fdb6e-6e67-402e-89ec-f7738b8127b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLEAR</value>
      <webElementGuid>589d64c6-512c-4263-835d-c94577ea540b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8e64d09e705fc5363521d56667356c3a</value>
      <webElementGuid>4d7f52e9-04ae-46c2-9872-8a1582bb3f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@onclick = 'clearSearch()']</value>
      <webElementGuid>dfc3f991-90c1-4210-b73c-7532f77c885e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@onclick = 'clearSearch()']</value>
      <webElementGuid>71f29704-bcb2-4248-8d13-93ea2ddcedcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CLEAR' or . = 'CLEAR')]</value>
      <webElementGuid>479272ad-7443-4417-aa25-8dbcf8176b92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
