<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Send_to_MaximEyes</name>
   <tag></tag>
   <elementGuidId>37748dd8-a201-4af5-ad07-a0b645ecd3c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@title=&quot;Send to MaximEyes&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@title=&quot;Send to MaximEyes&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>90549e9d-635e-48d3-b759-08e71af5d2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Evaa-Mike.svg</value>
      <webElementGuid>d794b7cc-cbeb-4578-9231-c72cbb37eec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>maximeyes-logo</value>
      <webElementGuid>3d1b7e7a-a0db-4447-87b8-fb85bf0b4590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4</value>
      <webElementGuid>965260ad-4005-4596-a9b6-093fa9ad01a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c8f53b12b9608ce24f3f03b1a319280e</value>
      <webElementGuid>4ab5d74b-61d8-4767-84be-aae9604d110f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@title=&quot;Send to MaximEyes&quot;]</value>
      <webElementGuid>18d047db-2b52-43ab-a825-0341aa7546ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>1461fac5-25b1-494d-a807-6d0edf7b40f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@title=&quot;Send to MaximEyes&quot;]</value>
      <webElementGuid>931becf0-0017-45da-bf9c-27a84af117a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title=&quot;Send to MaximEyes&quot;]</value>
      <webElementGuid>56a4ae6d-e1ea-4347-bd8f-6a554758735d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
