<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Copy_Note</name>
   <tag></tag>
   <elementGuidId>65b2a9e4-5a32-4336-80b1-57ca04245ca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='btn-copy-${type}'][@title=&quot;Copy Note&quot;][count(. | //*[@ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame']) = count(//*[@ref_element = 'Object Repository/EVAAPage/EVAA Scribe/iFrame'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-copy-${type}'][@title=&quot;Copy Note&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bdc0c60d-10ab-49c8-960b-95ab1467f303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Evaa-Mike.svg</value>
      <webElementGuid>186f466c-738c-4c7b-bc87-2835b43ef348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>maximeyes-logo</value>
      <webElementGuid>4fc0f3ed-78e8-4ff1-8a58-164f95f1667a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4</value>
      <webElementGuid>077bb656-0c8d-4364-b208-4327861ecd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c8f53b12b9608ce24f3f03b1a319280e</value>
      <webElementGuid>5c135270-0969-4da6-9d54-83a7ecae093a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='btn-copy-${type}'][@title=&quot;Copy Note&quot;]</value>
      <webElementGuid>29a85a9e-0876-49e6-831a-65ad62e3d8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>9d995ddd-52a4-4b59-ac94-9b6b687ef681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-copy-${type}'][@title=&quot;Copy Note&quot;]</value>
      <webElementGuid>050c6d8a-67b2-4352-852d-2fe0b22e45dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id='btn-copy-${type}'][@title=&quot;Copy Note&quot;]</value>
      <webElementGuid>4709051f-301c-4772-a791-4a0913be3f25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
