<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EncounterPatientHeader</name>
   <tag></tag>
   <elementGuidId>04a3399b-b131-4260-b9c7-7c04c375c538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCreateANewEncounter</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'btnCreateANewEncounter']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;patientEncounterHeader&quot;]//span[contains(@class,&quot;patientName&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;CREATE NEW&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c16dc38-8d6d-4373-a183-b1309344dcc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>edae4d32-166c-4e79-a737-9fcd4bc22b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmbar-btn-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2b2e68e4-4b22-4276-a0c8-f70772ecfe94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CREATE NEW</value>
      <webElementGuid>b300d77b-2d7e-4da0-ad82-259981ef5af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold font20 hide-confirmation ignore-action-toggle margin-right-10px margin-top-10px  notifationButton</value>
      <webElementGuid>088a3997-0303-4bad-a5ab-b50594bac23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>a1a0038c-c8ac-453a-be1f-d002b41b3e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCreateANewEncounter</value>
      <webElementGuid>81ea18fe-68b2-489a-a8cd-579e5940977a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCreateANewEncounter&quot;)</value>
      <webElementGuid>36d412c5-c2b8-4f83-bf98-7eaa6778dd1a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
