<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ProviderId</name>
   <tag></tag>
   <elementGuidId>69cf0b53-29d9-4e7a-ac4f-c8c5404e8c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NewPE_ProviderID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NewPE_ProviderID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NewPE_ProviderID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>27d6c91c-d69c-4c42-a0c2-aaeec131015f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewPE_ProviderID</value>
      <webElementGuid>2dfaaa61-cb62-460f-9f85-6cb62d75cfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wm-hide</value>
      <webElementGuid>f9017834-0506-4519-8122-6e0b9e6affd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6bac8efe-559c-481f-b37d-48b9d7dc3788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field ProviderID must be a number.</value>
      <webElementGuid>cf3b6a6c-d635-42a8-9132-af14c9d825cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Provider is required</value>
      <webElementGuid>1cd0a740-6438-4ce6-80b8-160b4a132c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>7a35c8cf-3d85-4dc0-a12a-9aa68bbdc25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7378c235-c077-4969-8a66-68718a812e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Provider is required</value>
      <webElementGuid>814f8a88-8586-4c0a-bd71-1edee4161bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProviderID</value>
      <webElementGuid>7d2f72b1-e873-47c9-ae33-bf2c5d6ce4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jack JayShreya C</value>
      <webElementGuid>acffc697-6846-47ee-839d-e60de28a378e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewPE_ProviderID&quot;)</value>
      <webElementGuid>07abca59-b620-4fc1-bdc9-0bd1d75d5286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NewPE_ProviderID']</value>
      <webElementGuid>d855874a-53c1-4fa5-8490-ac882ee1cb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_NewPatientEncounter']/div/div/div/div/div/div/div/div[2]/div/div[3]/div/span/select</value>
      <webElementGuid>2b228fe5-1552-4f16-ac1c-6b8e31e5ec1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provider'])[5]/following::select[1]</value>
      <webElementGuid>fdd5ecfc-2f8f-4226-b404-ca1d9192b51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam Date'])[1]/following::select[1]</value>
      <webElementGuid>034ac7a8-1c54-4198-aa6b-de3755e55c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technician'])[1]/preceding::select[1]</value>
      <webElementGuid>2a10311c-b696-4fc0-8a25-a01f0c856a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referring physician'])[1]/preceding::select[2]</value>
      <webElementGuid>de3b6d7a-c976-49df-988b-742a2bb6df94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/select</value>
      <webElementGuid>ea1e02bc-9bbd-4603-ae39-2f369d06f862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'NewPE_ProviderID' and @name = 'ProviderID' and (text() = 'Jack JayShreya C' or . = 'Jack JayShreya C')]</value>
      <webElementGuid>4d286f7f-7362-499a-96a8-e57f40ec68cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
