<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Encounter Type_EncounterTypeID</name>
   <tag></tag>
   <elementGuidId>f1cc8955-26b7-4991-82b4-5ee25904f357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EncounterTypeID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EncounterTypeID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EncounterTypeID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>50ac4b9b-5d2e-4671-8b66-c2925f7b2cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc269483-0ae7-4988-9f74-31126a71347b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field EncounterTypeID must be a number.</value>
      <webElementGuid>ed70a288-808b-4afc-8129-08abd51b94c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Encounter Type is required</value>
      <webElementGuid>93ef44f5-2a7d-4255-960f-d3f740b4cdad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EncounterTypeID</value>
      <webElementGuid>8e84d3f9-6c01-4f03-9953-2b57e098a6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EncounterTypeID</value>
      <webElementGuid>9612ca3f-c29a-4408-84e0-80dc6ab02f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>encounterTypeChange(this)</value>
      <webElementGuid>5081bc38-1a54-4a5d-a573-65c37f4da4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annual Vision ExamAnnual Vision Exam - TrainingCL Follow UpGlasses CheckMedical ExamNew Patient Exam</value>
      <webElementGuid>3c06dcb6-1d11-42f5-a5b7-34cf8fde92f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EncounterTypeID&quot;)</value>
      <webElementGuid>8cd7e61e-3087-4100-a06a-3c0648bfd637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EncounterTypeID']</value>
      <webElementGuid>f1d63bed-13d9-4536-ace0-5db1111ed78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_NewPatientEncounter']/div/div/div/div/div/div/div/div[2]/div/div/div/span/select</value>
      <webElementGuid>e136d727-7b6a-45e6-92e7-ae02d4c91593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encounter Type'])[1]/following::select[1]</value>
      <webElementGuid>5183593b-8350-4424-a257-f55624e4e8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam Location'])[1]/preceding::select[1]</value>
      <webElementGuid>a8b2de28-0a48-4110-85c8-ef611852fa71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam Date'])[1]/preceding::select[2]</value>
      <webElementGuid>edad4363-dd5a-4ea8-b58a-87201ae8b24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/select</value>
      <webElementGuid>e6f1e848-3481-43eb-aadd-b091d1336fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EncounterTypeID' and @name = 'EncounterTypeID' and (text() = 'Annual Vision ExamAnnual Vision Exam - TrainingCL Follow UpGlasses CheckMedical ExamNew Patient Exam' or . = 'Annual Vision ExamAnnual Vision Exam - TrainingCL Follow UpGlasses CheckMedical ExamNew Patient Exam')]</value>
      <webElementGuid>63683ecc-0a16-4ed5-84d5-6c6c11b9db61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
