<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PracticeLocationID</name>
   <tag></tag>
   <elementGuidId>b80c7550-010e-44e2-bbb9-00647ba43137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NewPE_PracticeLocationID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NewPE_PracticeLocationID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NewPE_PracticeLocationID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23249aa7-6aad-4223-a8d5-84674af0a806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewPE_PracticeLocationID</value>
      <webElementGuid>3d07af4c-20d2-465f-8755-a5841ace78cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f082182-7a1b-4b85-b3d7-99f6400c44ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field PracticeLocationID must be a number.</value>
      <webElementGuid>554a71d0-3eb6-474a-8420-1d4c668ca384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Exam Location is required</value>
      <webElementGuid>b5ebd695-aa88-4c4f-84ac-7b7ee1692623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>630c773f-f6d0-42d7-a96f-6c706b37c9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cc6e4164-b114-4aae-9d1b-a25a1cc5d666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Exam Location is required</value>
      <webElementGuid>9ef4f509-506f-4ba3-b47c-2902dd7c82aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PracticeLocationID</value>
      <webElementGuid>0f2ca140-a8bc-4ec2-903a-8a7ae1bdc1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>peLocationChangeEvent(this)</value>
      <webElementGuid>ac5426b6-ba2a-45f3-a4a4-beeef129d071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABeavertonHillsboro</value>
      <webElementGuid>3da3a18c-5cba-4ef8-9e76-4259d35c0630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewPE_PracticeLocationID&quot;)</value>
      <webElementGuid>b257ade4-d9ea-4a92-aed3-8705487b44b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NewPE_PracticeLocationID']</value>
      <webElementGuid>c852555c-8b07-4f54-a7b2-e4ac2a5674c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_NewPatientEncounter']/div/div/div/div/div/div/div/div[2]/div/div[2]/div/span/select</value>
      <webElementGuid>959c6c36-e4eb-45de-b9ff-2851c8d68a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam Location'])[1]/following::select[1]</value>
      <webElementGuid>2bd84001-6a64-4134-810d-a2ad2a2fcf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encounter Type'])[1]/following::select[2]</value>
      <webElementGuid>1791aca5-15c7-4e41-80cb-9ff7e3d67ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam Date'])[1]/preceding::select[1]</value>
      <webElementGuid>8d1939ad-b254-42cc-a59d-505fb1512a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provider'])[5]/preceding::select[1]</value>
      <webElementGuid>80716f67-c35c-40cb-ae36-550e6a950344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/select</value>
      <webElementGuid>2df7ea14-05b4-44b1-b050-cd6b7533b3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'NewPE_PracticeLocationID' and @name = 'PracticeLocationID' and (text() = 'ABeavertonHillsboro' or . = 'ABeavertonHillsboro')]</value>
      <webElementGuid>21aa4ea1-25ec-470d-abdc-8f44b2cda211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
