<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Technician_NewPE_TechnicianID</name>
   <tag></tag>
   <elementGuidId>4d26a5aa-576b-4389-a16b-2372c9881cb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NewPE_TechnicianID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NewPE_TechnicianID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NewPE_TechnicianID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5f2a6720-f036-4950-b60a-e87e44824962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewPE_TechnicianID</value>
      <webElementGuid>b03a8fe5-a2f4-4f86-a5ea-a4c2ab3225b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wm-hide</value>
      <webElementGuid>e9d1d52a-dcca-4693-8f2a-e75dc828aab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b359aa82-ad2e-439a-b7c6-f72a67d28f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field TechnicianID must be a number.</value>
      <webElementGuid>82962666-e67a-4e77-941e-32228398034e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TechnicianID</value>
      <webElementGuid>7f10d784-053b-43be-b634-84285cbc5a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Shreya C</value>
      <webElementGuid>44b50600-c61e-47e9-8691-23936e811590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewPE_TechnicianID&quot;)</value>
      <webElementGuid>00b6ab34-892f-464d-82f2-51e3dfb9f871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NewPE_TechnicianID']</value>
      <webElementGuid>9fa47b8f-38e0-4480-8192-6bdb25cff69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_NewPatientEncounter']/div/div/div/div/div/div/div/div[2]/div/div[3]/div[2]/span/select</value>
      <webElementGuid>b2823ee4-3597-42be-9393-21828a1beb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technician'])[1]/following::select[1]</value>
      <webElementGuid>1ed0329e-13c3-436e-a291-c691b0638847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provider'])[5]/following::select[2]</value>
      <webElementGuid>c590a6fc-352b-4083-969f-04c2dade6598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referring physician'])[1]/preceding::select[1]</value>
      <webElementGuid>0fda3df3-0de7-4bf1-acbc-fc153146e5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/select</value>
      <webElementGuid>ea7701c3-ec69-448b-a286-3fc19db66a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'NewPE_TechnicianID' and @name = 'TechnicianID' and (text() = '--Select--Shreya C' or . = '--Select--Shreya C')]</value>
      <webElementGuid>c2343bbf-0994-4f0a-8c4f-cd4aa2383c45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
