<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Allergies</name>
   <tag></tag>
   <elementGuidId>b85ebc34-c1c2-4dee-8e8b-8d5334170322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(3) > .list-decimal li[contenteditable=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[*/span[text()='Allergies:']]/following-sibling::ol//li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>ol >> internal:has-text=/^Allergies$/ >> internal:role=listitem</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f81dd3e5-ba72-424a-a346-c924d2bade48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b43a2be-2762-4ffe-a56f-ed8724c1ad2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-black</value>
      <webElementGuid>2cfc79e3-b2a1-472f-ae54-52b3eed1f028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fcaa5d2527f2b04e58938d4fe1728e24</value>
      <webElementGuid>dcd05880-807e-4fcf-a193-d12ee8617864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 3)]/*[@class and contains(concat(' ', normalize-space(@class), ' '), ' list-decimal ')]//li[@contenteditable = 'true']</value>
      <webElementGuid>25dd7300-b374-47a5-8989-ec48f826b25d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[*/span[text()='Allergies:']]/following-sibling::ol//li</value>
      <webElementGuid>bcfcf711-9490-4c01-b3a5-cd707e7fd199</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
