<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Medications</name>
   <tag></tag>
   <elementGuidId>bc7a704e-85fa-45f9-924c-42f227605f30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>237d3584-1723-473e-bf4f-6ec296cf6451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brand Name: Pat a day</value>
      <webElementGuid>bfbab470-44a3-480a-874e-b5962979b419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d919c45cdb61e1dfdd5df8e916ac87bf</value>
      <webElementGuid>5aece70e-e914-4aa5-be9d-c424f1fb7863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      <webElementGuid>fb13b025-54c8-4e2b-926c-8e521d684697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[*/span[text()='Medications:']]/following-sibling::ol//li/span[@contenteditable=&quot;true&quot;]/span</value>
      <webElementGuid>c303fd26-134f-41fa-9c06-0d20e9f800d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
