<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Refractions</name>
   <tag></tag>
   <elementGuidId>76b80dfd-49a5-4f02-b00c-c6109b7ce6b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[*/span[text()='Refractions:']]/following-sibling::div/div[@class=&quot;text-sm text-black&quot;]/span[@class=&quot;text-sm text-black&quot;][@contenteditable=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[*/span[text()='Refractions:']]/following-sibling::div/div[@class=&quot;text-sm text-black&quot;]/span[@class=&quot;text-sm text-black&quot;][@contenteditable=&quot;true&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b68f71b0-a85c-4c0d-99b5-b77f0eb74ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-black</value>
      <webElementGuid>3e2a8109-5a30-406f-b63e-fcad65f6debe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e841ce33537bcd0ea05caf1c32619e6a</value>
      <webElementGuid>974a2e95-f95f-43ab-80c0-15f3270600d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[*/span[text()='Refractions:']]/following-sibling::div/div[@class=&quot;text-sm text-black&quot;]/span[@class=&quot;text-sm text-black&quot;][@contenteditable=&quot;true&quot;]</value>
      <webElementGuid>abf85257-216c-4e74-b423-93fbbf4924e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[*/span[text()='Refractions:']]/following-sibling::div/div[@class=&quot;text-sm text-black&quot;]/span[@class=&quot;text-sm text-black&quot;][@contenteditable=&quot;true&quot;]</value>
      <webElementGuid>2fa839e9-8618-4530-b5a5-24e7d6452880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
