<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_PatientName</name>
   <tag></tag>
   <elementGuidId>baefb876-1e43-495c-9179-efcd5191608a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[@id=&quot;header-patient-name&quot;][contains(text(),'${ptName}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id=&quot;header-patient-name&quot;][contains(text(),'${ptName}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[@id=&quot;header-patient-name&quot;][contains(text(),'${ptName}')]</value>
      <webElementGuid>f84f33f3-79e0-43c2-b393-d049d7a6fe0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EVAAPage/EVAA Scribe/iFrame</value>
      <webElementGuid>419526ce-1a00-42e0-b97b-2fef5f73599e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id=&quot;header-patient-name&quot;][contains(text(),'${ptName}')]</value>
      <webElementGuid>a4707971-d9d3-43f0-b180-6bad1e3672bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id=&quot;header-patient-name&quot;][contains(text(),'${ptName}')]</value>
      <webElementGuid>b4e5b07f-6c38-4648-b1ab-032bed22c577</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
