<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WorkQueue</name>
   <tag></tag>
   <elementGuidId>02790d38-713d-4d98-9050-257d97ed80bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id=&quot;idtblquicklinks&quot;][count(tbody/tr) > 1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc23ad43-ebb6-411d-9d7a-be03f314f1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>cfc96a64-31d4-4000-9586-2f79811b1598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>528a8a4b-d803-4b89-8b93-039b8dbd16bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>67ddf3c7-9bd4-457a-9fc3-651d277551a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>effe3615-cb77-43a2-a61f-baf626720bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b366e5cb-ec7f-4a7c-a8d7-5dddde3e75fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>f159c527-4574-4fdd-919a-80b51aecedb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LastName&quot;)</value>
      <webElementGuid>1cd8c2a2-81da-4f2f-9c3c-d0867fd589d6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
