<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first_Tr_EncounterGrid</name>
   <tag></tag>
   <elementGuidId>c8127d59-c1c5-4464-959b-cb6c86f8062d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[@id = 'EncounterGrid']//div[starts-with(@class,&quot;dx-datagrid-rowsview&quot;)]//table/tbody/tr[not(contains(@class,'dx-freespace-row'))])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.dx-data-row:nth-child(1) .hxExamNumbers.underline[role=&quot;gridcell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;100889&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f7285e6b-abbd-4fe7-affa-9a9d565a41b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline cursor-pointer hxExamNumbers</value>
      <webElementGuid>a62da4a7-2ea3-432f-aa06-4907ead533b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2456b45b-d308-45f3-8db4-23f756fbf1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>9911b486-fea0-4100-a488-d11cd9a24414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3e5b1991-89af-4d0a-96c3-a4fc74e6c95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa604140-87bf-4864-aa76-d93a2e66a5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100889</value>
      <webElementGuid>b4d7d8b4-9f9e-4360-be52-276e9b2f217c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cfc00b4d0cc40d685fbb2f4506e1f25b</value>
      <webElementGuid>cec970a4-e642-43c5-8fec-5710edb7d67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' dx-data-row ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hxExamNumbers ') and contains(concat(' ', normalize-space(@class), ' '), ' underline ') and (@role = 'gridcell')]</value>
      <webElementGuid>96df1b9c-5d52-49e1-a0c4-d5ad6f23adab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' dx-data-row ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hxExamNumbers ') and contains(concat(' ', normalize-space(@class), ' '), ' underline ') and (@role = 'gridcell')]</value>
      <webElementGuid>1f8060b5-3e2a-4a1f-b2ec-18d368e2aa74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
