<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_EncounterId</name>
   <tag></tag>
   <elementGuidId>129fc674-b932-494a-abe6-2854c02a1afa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'EncounterGrid']//div[starts-with(@class,&quot;dx-datagrid-rowsview&quot;)]//table/tbody/tr[not(contains(@class,'dx-freespace-row'))]/td[1][text()='${encounterId}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.dx-data-row:nth-child(1) .hxExamNumbers.underline[role=&quot;gridcell&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'EncounterGrid']//div[starts-with(@class,&quot;dx-datagrid-rowsview&quot;)]//table/tbody/tr[not(contains(@class,'dx-freespace-row'))]/td[1][text()='${encounterId}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;100889&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6149e2e7-68d9-4cc1-bd7e-da315b3e3832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline cursor-pointer hxExamNumbers</value>
      <webElementGuid>b7ba9d20-932d-4c3c-b798-b500c8ec9a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7e6220ac-17ce-4b42-a8b4-efb984f29a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>cb8284a6-8616-4db9-aff3-32e7574b4732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0f2e3641-6fef-4f30-b192-f47eac02c2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>871740f3-50f9-4418-9162-d383e9b1968f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100889</value>
      <webElementGuid>9f854725-3311-41ef-9cee-2bba50b24645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cfc00b4d0cc40d685fbb2f4506e1f25b</value>
      <webElementGuid>99e66585-d665-457c-86be-33b44216a296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'EncounterGrid']//div[starts-with(@class,&quot;dx-datagrid-rowsview&quot;)]//table/tbody/tr[not(contains(@class,'dx-freespace-row'))]/td[1][text()='${encounterId}']</value>
      <webElementGuid>225ec490-6faf-43fd-a83a-6d1543244f25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'EncounterGrid']//div[starts-with(@class,&quot;dx-datagrid-rowsview&quot;)]//table/tbody/tr[not(contains(@class,'dx-freespace-row'))]/td[1][text()='${encounterId}']</value>
      <webElementGuid>5b8a6830-acdd-49ad-ba26-2f6ec56fb725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
