<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_FirstEncounterId</name>
   <tag></tag>
   <elementGuidId>7db24a1e-bd01-49fd-b82a-eda4fcf5a526</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id = 'EncounterGrid']//div[starts-with(@class,&quot;dx-datagrid-rowsview&quot;)]//table/tbody/tr[not(contains(@class,'dx-freespace-row'))]/td[1])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@id = 'EncounterGrid']//div[starts-with(@class,&quot;dx-datagrid-rowsview&quot;)]//table/tbody/tr[not(contains(@class,'dx-freespace-row'))]/td[1])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>97e239e8-c2e3-4e55-8b68-80e6afbd2486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline cursor-pointer hxExamNumbers</value>
      <webElementGuid>134668c1-4d0b-49c4-93a9-4646b32a886f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fd365f3d-3012-4016-afb6-a93a0b0640dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>18dcb295-12f7-4b4a-9840-c9c6dd4681c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3683a2fc-abb8-49fb-b775-1fb930d81d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8dd027d-0296-45a3-9dc9-4e2907ad71ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100889</value>
      <webElementGuid>354a90ce-c0bf-4d88-8b0e-609424c4bc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cfc00b4d0cc40d685fbb2f4506e1f25b</value>
      <webElementGuid>c0cd51b6-cb3f-46eb-9e19-82a1944d815f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id = 'EncounterGrid']//div[starts-with(@class,&quot;dx-datagrid-rowsview&quot;)]//table/tbody/tr[not(contains(@class,'dx-freespace-row'))]/td[1])[1]</value>
      <webElementGuid>b3756f74-c378-4469-8306-4f23db12676c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//*[@id = 'EncounterGrid']//div[starts-with(@class,&quot;dx-datagrid-rowsview&quot;)]//table/tbody/tr[not(contains(@class,'dx-freespace-row'))]/td[1])[1]</value>
      <webElementGuid>96663e46-c2bd-4bac-8dde-b149ce4c0f30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
