<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Chart Number</name>
   <tag></tag>
   <elementGuidId>2e32a9de-0907-40bc-86bf-9f119024997e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ChartNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ChartNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Chart Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3d98163-d7d2-4fca-aee6-253f3bfc2c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChartNumber</value>
      <webElementGuid>15e11dc6-1b68-4cdd-8575-287458866352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ChartNumber</value>
      <webElementGuid>68122a7c-6c58-4275-9546-578dc990e876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Chart Number</value>
      <webElementGuid>90878a44-a775-49f2-a942-b537a3d18bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>09cf1cdd-4edf-43ff-b5be-227a98b8aaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9c1fad6-5c7d-4edb-bacf-b8b43c47f43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>dd182c28-a4a4-441e-9f1a-89a81cbbfec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c30d5e23ab2fc8e32cc34ce4f13e7972</value>
      <webElementGuid>15bf3971-673e-4645-ad78-fa570e8d1eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ChartNumber']</value>
      <webElementGuid>8eb68626-99e9-4f8d-a568-61ac938d58e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ChartNumber']</value>
      <webElementGuid>d425b226-4b5d-4acd-bdf4-3955a6250afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChartNumber' and @name = 'ChartNumber' and @placeholder = 'Chart Number' and @type = 'text']</value>
      <webElementGuid>08db9840-e80f-45af-93f1-0b6881891bde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
