<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divReviewOfSystems</name>
   <tag></tag>
   <elementGuidId>ca83a3f8-7b80-41dd-a9f7-22da4bc199cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@data-elementname=&quot;Review_of_Systems_Brief&quot;])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@data-elementname=&quot;Review_of_Systems_Brief&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-elementname=&quot;Review_of_Systems_Brief&quot;])[1]</value>
      <webElementGuid>bfbf7788-7bf7-4c01-bdf2-2149eb9b0826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@data-elementname=&quot;Review_of_Systems_Brief&quot;])[1]</value>
      <webElementGuid>61db538c-f8f5-43a9-8d4d-a448005e74d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//div[@data-elementname=&quot;Review_of_Systems_Brief&quot;])[1]</value>
      <webElementGuid>ca2a5962-e3c5-4ca6-ab19-bd8d74cc93b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
