<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Review_of_Systems</name>
   <tag></tag>
   <elementGuidId>32aa14c9-db72-4642-959b-e5c5b8e2fbe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\34 112\.Review_of_Systems_Brief\.ENDOCRINE_NOTES&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and contains(@name, 'Review_of_Systems_Brief.${inputId}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*contains([@name , 'Review_of_Systems_Brief.${inputId}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;\34 112\.Review_of_Systems_Brief\.ENDOCRINE_NOTES&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>511f91b7-6772-439c-9cdc-db6cc581457c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5035b6b7-4c36-42b2-87bb-ad7c3cf912c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61adff4f-584a-4507-bc46-092cd0c7a8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8000</value>
      <webElementGuid>dc0ec8ae-8c5e-4df1-9638-79ffb83257a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c45fe452-91c1-4287-b0ee-3fdb8531a4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50076a98-1855-4f1d-83a5-ff470cf45e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>5fa6cc2e-57a9-428e-a269-cd6c94b26194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Review_of_Systems_Brief.${inputId}</value>
      <webElementGuid>40973fed-6285-4fc5-9592-6a80844b877f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9538</value>
      <webElementGuid>a0349e26-2111-46ff-a74d-2b705038e855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>97230c56-e72e-41c3-9ff6-5ee58ee03ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>1324</value>
      <webElementGuid>6e1b2985-d416-46ed-9807-565a093582b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e16eef54-f1ec-4ebd-ba11-d93f81715a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eyetype</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>405c2417-2b37-4c11-9ead-48d9b0732376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>4173</value>
      <webElementGuid>068126d7-240c-47e9-afc8-d2d47d4376d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-supportclearbtn</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>594aacbc-ad7e-4ff0-a79b-0407161a06a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>4112</value>
      <webElementGuid>3892a1d7-d93f-49e9-be94-2886318edbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clearable</value>
      <webElementGuid>a7a2c86b-7882-4bd8-937c-db203a036980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1a1771c0-6d85-4311-a416-e759e5cf1b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Review_of_Systems_Brief.${inputId}</value>
      <webElementGuid>597023f3-f9b6-447d-b118-c87e174e3ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>${inputId}</value>
      <webElementGuid>e1303b26-a831-429e-82de-9dedfc0eaef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Review_of_Systems_Brief</value>
      <webElementGuid>11723f93-18be-4731-89f4-a45e7020dda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0115f819-dce8-41eb-8599-334964439f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-47ce3a4072e0c200a19dc737cf5fdf0c</value>
      <webElementGuid>605f6784-04c9-4703-8d56-a7354b84612b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*contains([@name , 'Review_of_Systems_Brief.${inputId}')]</value>
      <webElementGuid>e667b65e-354a-42c6-af7f-5bfd28c3e21f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*contains([@name , 'Review_of_Systems_Brief.${inputId}')]</value>
      <webElementGuid>a970ffb3-5eb2-4145-a8ac-00903440cdec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and contains(@name , 'Review_of_Systems_Brief.${inputId}')]</value>
      <webElementGuid>c8741934-4620-4237-990e-1e4567eb5b94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
