<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Additional_Notes_ROS</name>
   <tag></tag>
   <elementGuidId>e3380c2f-d11e-4492-a6c5-8622faf3755d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@name, 'Review_of_Systems_Brief.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[contains(@name , 'Review_of_Systems_Brief.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a9ef91e8-d975-49c7-a01e-2996f9eaa8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>877a3908-6b51-4292-9b2a-6f6843ce34fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d3fa5eb-0014-4e5e-9e68-b33fcd308c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>28d4f1cc-41ba-4cb6-a577-3e9374878818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8000</value>
      <webElementGuid>3b616abc-1a7f-4cf7-a4d6-acf2e6187e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>c9095a0e-f041-444e-b659-97cbb6792b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Review_of_Systems_Brief.ADDITIONAL_NOTES</value>
      <webElementGuid>7f9f82fd-5300-4d7c-81b8-fbcc06b8545b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9547</value>
      <webElementGuid>cbc86fd5-860a-4aac-a271-6ed3821cf1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_ctrldispname</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>2278b3a7-a256-4eda-b604-c120800afdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1be8cbd5-791e-4bcc-89ce-bf40357c5820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>1336</value>
      <webElementGuid>504c4501-bf76-40fa-a920-59a555eaa692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>733c46b5-8ae1-44aa-b0a5-c53c9399bb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eyetype</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>d1a9d3e0-aca3-4da5-b911-95faa78b6ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>4173</value>
      <webElementGuid>4b35006a-2f1b-481e-a4fb-0292671efa86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-watermark</name>
      <type>Main</type>
      <value>Additional Notes</value>
      <webElementGuid>d856f761-1ca5-416c-949c-0a4bd21a82d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>4112</value>
      <webElementGuid>bd1c39dc-c2a8-4b1a-80ce-a67c1133f253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>eb84efe7-1f20-46f3-af13-01801e701084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-includeinsummaryelm</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>f4cbcc32-024d-48fe-bc10-c0c10ca14e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Additional Notes</value>
      <webElementGuid>59c41ca3-12a8-40f2-b1d3-03723057d700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>06ae7ab3-5228-42cd-a57b-7daf08257e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Review_of_Systems_Brief.ADDITIONAL_NOTES</value>
      <webElementGuid>76ae1224-ad2f-47f7-9956-6303dbee46ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>ADDITIONAL_NOTES</value>
      <webElementGuid>4f59d228-7cde-4f0c-99ed-d9a035ccf2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Review_of_Systems_Brief</value>
      <webElementGuid>03310e4f-9f92-4349-a3c3-9e2e2bfbaa87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5cd5124d-fb5e-4500-be97-18994ee6fa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1f594c6af9ac361c9865fb05d5974294</value>
      <webElementGuid>331aa48d-3a7e-4a9b-822d-9d03448d8403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@name , 'Review_of_Systems_Brief.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      <webElementGuid>9cc01177-c5f0-4330-9543-afbf2e35e6e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[contains(@name , 'Review_of_Systems_Brief.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      <webElementGuid>69e6a5e0-b1fd-4f54-8273-0cfe16d79ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[contains(@name , 'Review_of_Systems_Brief.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      <webElementGuid>1417d26a-ec81-43f3-92de-4f72821d55b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
