<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Additional_Notes_ROS</name>
   <tag></tag>
   <elementGuidId>e3380c2f-d11e-4492-a6c5-8622faf3755d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@name, 'Review_of_Systems_Brief.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[contains(@name , 'Review_of_Systems_Brief.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8b1101a0-6c6f-4d42-8700-9a7a8e7eee66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sysdef</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e01f467d-bc71-4730-a93a-cc8f060b0a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reffield</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f2076266-c96c-4381-a2ff-5b899ba81d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isrefered</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3ffc58f8-c9aa-4f17-8c03-6d278f6099a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8000</value>
      <webElementGuid>7d9614b2-9bec-4db1-a09c-7122b77ad87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-defaultdatatype</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>571655d6-319b-4fde-abbb-4fbd644db198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Review_of_Systems_Brief.ADDITIONAL_NOTES</value>
      <webElementGuid>93328d7d-1131-4eab-a50b-4dc04b3bbff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9547</value>
      <webElementGuid>7a0fb5ea-6a3a-42f0-9920-04fdd0c89686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ec_ctrldispname</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>94314eaa-70b9-4fa8-90a0-8be82d374258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canbehidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0de5e2e0-cb61-4019-9f62-d1e9af1fad78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cid</name>
      <type>Main</type>
      <value>1336</value>
      <webElementGuid>3b851b66-8b22-495c-b305-6f165b63593c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isreadonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b82e727-e7b3-49f1-8d73-9ff08ad37847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eyetype</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>424c1639-ec43-434b-b853-f15f855c6e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementid</name>
      <type>Main</type>
      <value>4173</value>
      <webElementGuid>a480ed57-674a-4606-9591-b78092a9ef08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-watermark</name>
      <type>Main</type>
      <value>Additional Notes</value>
      <webElementGuid>0fc5a9a0-783b-4728-b376-6214f8fde892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enc_elementpagerelid</name>
      <type>Main</type>
      <value>4112</value>
      <webElementGuid>1fa22979-402f-430b-841e-c2aac02b7c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>8010f9d1-118b-4dc8-bbfd-0ea5e934d01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-includeinsummaryelm</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>3c276feb-da02-4c78-9ff8-d1c3d51d4626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Additional Notes</value>
      <webElementGuid>a96de028-1efa-42cd-acf7-eef839a30763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refelmid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>28b2e662-3a47-4b4e-8c8f-0d83a035dc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-askey</name>
      <type>Main</type>
      <value>~F_F~Review_of_Systems_Brief.ADDITIONAL_NOTES</value>
      <webElementGuid>79fa5a1d-e294-4c60-9840-0cd05d447b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actualname</name>
      <type>Main</type>
      <value>ADDITIONAL_NOTES</value>
      <webElementGuid>934d41f6-5e68-46f1-87c1-afd245701808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elementname</name>
      <type>Main</type>
      <value>Review_of_Systems_Brief</value>
      <webElementGuid>0022219b-23d1-4e9a-9e1d-a4f30e4ba873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c1689811-e08a-4f08-819b-7b1dcac7f64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1f594c6af9ac361c9865fb05d5974294</value>
      <webElementGuid>195fe4ec-e85e-4e0b-a9a7-ed3dfa9fbe88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[contains(@name , 'Review_of_Systems_Brief.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      <webElementGuid>17876bca-bea6-405e-a008-136a80ebb2ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[contains(@name , 'Review_of_Systems_Brief.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      <webElementGuid>ff26dd7b-ad63-4a11-b03c-fafa4a6fb189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[contains(@name , 'Review_of_Systems_Brief.ADDITIONAL_NOTES') and @placeholder = 'Additional Notes']</value>
      <webElementGuid>f5ef22f9-ffef-4326-aa73-e369ce44c576</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
